### ISSUE TITLE
tuple in function declaration is not valid Python 3

### ISSUE THREAD

**Issue by ebirn** [CostaLab/reg-gen#106]
Using a tuple like this in the function declaration like this will not work in python 3
https://github.com/CostaLab/reg-gen/blob/d3086bd94779c00e5446f460a0cd32b2c79e1b75/rgt/THOR/dpc_help.py#L226

proposed fix:
```
-def _compute_pvalue((x, y, side, distr)):
+def _compute_pvalue(dist_tuple):
+    (x, y, side, distr) = dist_tuple
```

Best,
Erich

**Comment by ebirn** [comment]
ok, I'm closing this too then, as it is probably also covered by #12

**Comment by fabio-t** [comment]
Yep, but it's still appreciated ;)
