### ISSUE TITLE
USGC utilities require old libpng12.so.0 library

### ISSUE THREAD

**Issue by fabio-t** [CostaLab/reg-gen#108]
```
wigToBigWig: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

**Comment by analeighgui** [comment]
Any update on this? I got the same error when running THOR.

**Comment by fabio-t** [comment]
A symbolic link to one's own libpng library (eg, for Ubuntu 18.04 is `libpng16.so`) solves this issue. I don't think we should invest more energy into it, unless it is to provide pure-python implementations - efficient enough to ditch the USGC tools.
