### ISSUE TITLE
rgt-hint differential normalization confusion

### ISSUE THREAD

**Issue by davemcg** [CostaLab/reg-gen#114]
When should `factor1` and `factor2` be used? If the `BAM 1` has 2X the reads of `BAM 2` does rgt-differential take that info account? Or would I give `factor1` a value of `2` and `factor2` a value of `1`?

**Comment by davemcg** [comment]
Oops, reversed that. 

BAM1=200 reads
BAM2=100 reads
factor1=1
factor2=2

Yes? No?

**Comment by lzj1769** [comment]
Hi,

The normalization factors are based on TF activity scores, not on the number of reads.  Specifically, we first calculate the factor activity score under each condition using reads around the predicted binding sites, and then compute `factor1` and `factor2` with all TF scores and median-of-ratios method, as used in DESeq2.  Although we don't directly use the number of reads for calculation of normalization factors, we usually observe some relationships between them.

Best,
