### ISSUE TITLE
duplicate gene names warning

### ISSUE THREAD

**Issue by fabio-t** [CostaLab/reg-gen#117]
```
Warning: The gene RLF contains more than one matching IDs, both will be used.
```

These warnings can be a real nuisance. We should only print them when verbosity is set by the user.

**Comment by fabio-t** [comment]
Also please investigate the difficulty of getting non-capitalised gene names for appropriate organisms (eg, for mouse `RLF` should be `Rlf` - is the gene annotation being fetched for the right organism?)

**Comment by jovesus** [comment]
Yes. This is a topic we should talk about. The initial setup by Eduardo is
to convert all gene names to capitalized and then do the matching. If the
user specifies the organism properly, I don't see any problem. But it is
true that the output gene names are all capitalized and it is tricky to
convert them back to their original form.

*Joseph Chao-Chung Kuo*


Am Fr., 5. Apr. 2019 um 16:58 Uhr schrieb Fabio Ticconi <
notifications@github.com>:
