### ISSUE TITLE
Minimum coverage/number of reads for TF footprinting

### ISSUE THREAD

**Issue by josruirod** [CostaLab/reg-gen#118]
Hi, so I want to ask a question

Is there a minimum coverage or number of reads currently recommended for ATAC-seq TF footprinting analyses? I have doubts about testing this approach on some libraries, and I fail to find this info, so I have doubts whether it's worth to even try

Thanks for all the work and your availabilty!

**Comment by lzj1769** [comment]
Hi,

> Is there a minimum coverage or number of reads currently recommended for ATAC-seq TF footprinting analyses?

I would recommend taking 50 million reads as input for footprinting, as suggested by [ENCODE project](https://www.encodeproject.org/atac-seq/#standards). 

But, the coverage or number of reads might not be a good measurement about the ATAC-seq data quality. Instead, you can check the FRiP score (fraction of reads in called peak regions), which we found can be a good indicator of footprints prediction (see [Figure S21](https://static-content.springer.com/esm/art%3A10.1186%2Fs13059-019-1642-2/MediaObjects/13059_2019_1642_MOESM1_ESM.pdf)). Usually, FRiP>0.3 means your data is of high quality.

Best,
Li

**Comment by josruirod** [comment]
appreciate your comments, thanks
