### ISSUE TITLE
Python 3 Conversion

### ISSUE THREAD

**Issue by bheavner** [CostaLab/reg-gen#12]
I've encountered a few typos with setup.py when running with python 3.5. When I tried this:`python setup.py install --prefix=/local/tools/HINT-1.1.1 --rgt-data-path=/local/tools/HINT-1.1.1 --rgt-tool=hint`

I got the following error:

```
  File "setup.py", line 132
    except (BadOptionError,AmbiguousOptionError), e:
```

which I corrected by changing line 132 to:

```
except (BadOptionError,AmbiguousOptionError) as e:
```

then I got the following error:

```
  File "setup.py", line 398
    default_file_permission = 0644
                                 ^
SyntaxError: invalid token
```

which I corrected by changing line 398 and 299 to:

```
default_file_permission = 0o644
default_path_permission = 0o755
```

(apparently python3 doesn't like numbers beginning with 0. Octal numbers start with 0o)

then, the setup works. But then I get some errors when I attempt to run rgt-hint... I'll get to those in another issue.

**Comment by bheavner** [comment]
It looks like I've hit a block in my python3 efforts - ngslib, which contains BigWigFile and is imported in HINT/signalProcessing.py, appears to be a python 2.7 dependency...

**Comment by fabioticconi** [comment]
Hi @bheavner, sorry for the late reply. We currently only support python 2, and only on Linux. I'm closing #13 and #14 and renaming this issue so that you'll be notified when we get around to make the code python3-friendly.

**Comment by fabio-t** [comment]
Self note: there's a problem with `configparser.ConfigParser` (a library I've had to add as "bridge" between python2 and python3):

```
/home/fabio/.local/lib/python2.7/site-packages/rgt/Util.py:44: DeprecationWarning: You passed a bytestring as `filenames`. This will not work on Python 3. Use `cp.read_file()` or switch to using Unicode strings across the board.
  self.config.read(data_config_file_name)
/home/fabio/.local/lib/python2.7/site-packages/rgt/Util.py:47: DeprecationWarning: You passed a bytestring as `filenames`. This will not work on Python 3. Use `cp.read_file()` or switch to using Unicode strings across the board.
  self.config.read(data_config_file_name + ".user")
```

**Comment by fabio-t** [comment]
Pull request https://github.com/CostaLab/reg-gen/pull/46 has provided the first piece of the Python 3 puzzle. Some more work required on HINT, plus extensive testing, and then onto verifying each library's compatibility.

**Comment by fabio-t** [comment]
This now has higher priority. We'll probably drop Python 2.7 support and completely move to Python 3.

**Comment by fabio-t** [comment]
Finished with version 0.13.0.
