### ISSUE TITLE
installation issue of RGT 0.12.1: ngslib module

### ISSUE THREAD

**Issue by JulieHoang** [CostaLab/reg-gen#120]
Hi, 
I am installing rgt-hint but run into this error message when trying rgt-hint footprinting --help

File "/usr/local/lib/python2.7/dist-packages/RGT-0.0.1-py2.7-linux-x86_64.egg/rgt/HINT/signalProcessing.py", line 22, in <module>
    from ngslib import BigWigFile
ImportError: No module named ngslib
Do you have any suggestion to fix this?

**Comment by lzj1769** [comment]
Hi,

It seems you installed an old version of RGT.
In the latest RGT, we don't use ngslib anymore, if I remember correctly.

Can you try to re-install it as following?
```
pip uninstall RGT
pip install RGT --user
```
You might need to run `pip uninstall RGT` a couple of times until you cannot find RGT in your machine.

Best,
Li

**Comment by JulieHoang** [comment]
Thank you so much for the quick response. It's working now. Quick question, is the input bam file sorted or not? My input bam file is sorted b query (because I used Genrich to generate narrowPeaks file) and it give this error
$ rgt-hint footprinting --atac-seq --paired-end --organism=hg38 --output-location=./ --output-prefix=866 genrich_sorted_SRR7650816.bam 816.narrowPeaks 
The index file of genrich_sorted_SRR7650816.bam doesn't exist, generating with Pysam
[E::hts_idx_push] NO_COOR reads not in a single block at the end 5 -1
Traceback (most recent call last):
  File "/home/julie/.local/bin/rgt-hint", line 11, in <module>
    load_entry_point('RGT==0.12.1', 'console_scripts', 'rgt-hint')()
  File "build/bdist.linux-x86_64/egg/rgt/HINT/Main.py", line 90, in main
  File "build/bdist.linux-x86_64/egg/rgt/HINT/Footprinting.py", line 110, in footprinting_run
  File "build/bdist.linux-x86_64/egg/rgt/HINT/Footprinting.py", line 130, in atac_seq
  File "/home/julie/.local/lib/python2.7/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: failed to create index for "genrich_sorted_SRR7650816.bam": Resource temporarily unavailable\n'

**Comment by lzj1769** [comment]
Hi,

This error comes from Pysam, which is used to generate an index for your BAM file.
The index allows us to randomly access the BAM file.
From what I know, you need to sort the BAM file by coordinate before indexing it.

Best,
Li
