### ISSUE TITLE
RGT footprinting --atac-seq

### ISSUE THREAD

**Issue by rschwess** [CostaLab/reg-gen#123]
Hi,

Loved your paper. I'm trying to run the atac-seq footprinting but get basic complaints that I should rather input an experiment matrix. Following the DNase-seq examples in the tutorials I still couldn't get it to run.

rgt-hint footprinting --atac-seq --paired-end --organism=hg19 --output-location=./ --output-prefix=cd34_d10 CD34_D10_atac_merged_filtered.bam macs2_peakcall_ploidy_filtered.bed

Error Number: 2.
Program: rgt-hint.
Report: You must provide at least one and no more than one experimental matrix as input argument. 
Behaviour: The program will quit with exit status 0.

Cheers,
Ron

**Comment by lzj1769** [comment]
Hi Ron,

Which RGT version are you using?
Using the experimental matrix as input has been removed from RGT-hint if I remember correctly.

Best,
Li

**Comment by rschwess** [comment]
"HINT - Regulatory Analysis Toolbox (RGT). Version: 1.0.0"
The version I install by default using pip on python 2.7.5.
Should I try an older version?

**Comment by lzj1769** [comment]
the lastest RGT is v0.12.1, so obviously, a wrong RGT was installed.
can you try to re-install RGT as follows:
```
pip uninstall RGT
pip install RGT --user
```
