### ISSUE TITLE
"norm" argument in rgt-hint tracks for normalization

### ISSUE THREAD

**Issue by icanwinwyz** [CostaLab/reg-gen#125]
Hi 
Thanks for making this great tool. I have a question about the normalization using "rgt-hint tracks". In your tutorial (http://www.regulatory-genomics.org/hint/tutorial/), it said "Note that this command currently only supports bias correction and shifts of ATAC-seq.". However, in the help manual of the command, there is an argument, "--norm", showing "If set, the normalised signals from DNase-seq or ATAC-seq data will be generated. DEFAULT: False". Could you clarify can I normalize the signal when I convert the bam to bigwig using "rgt-hint tracks" with "--norm" turned on? 

I also checked the source code for this normalization and found that:
"if args.norm:
                    signal = reads_file.boyle_norm(signal)
                    perc = scoreatpercentile(signal, 98)
                    std = np.std(signal)
                    signal = reads_file.hon_norm_atac(signal, perc, std)"

Could you explain what is this normalization? Many thanks in advance!!

**Comment by lzj1769** [comment]
Hi,

> However, in the help manual of the command, there is an argument, "--norm", showing "If set, the normalised signals from DNase-seq or ATAC-seq data will be generated. DEFAULT: False". 

This is a mistake for help information, we will fix it later.

> Could you clarify can I normalize the signal when I convert the bam to bigwig using "rgt-hint tracks" with "--norm" turned on?

If you are processing ATAC-seq, then you can simply turn on --norm.

> I also checked the source code for this normalization and found that:
> "if args.norm:
> signal = reads_file.boyle_norm(signal)
> perc = scoreatpercentile(signal, 98)
> std = np.std(signal)
> signal = reads_file.hon_norm_atac(signal, perc, std)"
> 
> Could you explain what is this normalization? Many thanks in advance!!

This normalization aims to put the signals from different regions to the same scale [0, 1]. The detail can be found here:
https://academic.oup.com/bioinformatics/article/30/22/3143/2390674

Best,
Li
