### ISSUE TITLE
rgt-hint footprinting output scores?

### ISSUE THREAD

**Issue by YichaoOU** [CostaLab/reg-gen#128]
After running `rgt-hint footprinting`, I got .bed files. What are the scores in 5th col?

Thanks,
Yichao

**Comment by lzj1769** [comment]
it's the number of cut sites around the predicted footprint with extended 100 bp. 
you can use it to do some filtering about the footprints.

**Comment by davemcg** [comment]
Why do I have negative numeric values (as low at -40.3) at this column? Is there some kind of scaling applied?

Running footprinting as follows (0.12.3):

```
rgt-hint footprinting \
            --atac-seq \
            --paired-end \
            --organism=hg38 \
            --output-prefix {wildcards.sample} \
            --output-location=bulkATAC/HINT \
            {input.bam} \
            {input.peaks}
```
