### ISSUE TITLE
rgt-hint footprinting error PyX import fail

### ISSUE THREAD

**Issue by nfancy** [CostaLab/reg-gen#131]
Hi 

I have installed rgt with python2.7.15 but while trying to run rgt-hint footprinting I am getting er error that says it fails to import PyX. I tried to install PyX using pip but found it requires python3. Any suggestion to solve this?

Best wishes
Nurun

**Comment by lzj1769** [comment]
Hi,

we have removed pyx dependency but seems it's not fully removed from
rgt-hint.
At the moment, you can try to install old pyx, for example, pip install
PyX==0.12
we will fix this soon.

Best,

*______________________________*
Zhijian Li
Institute for Computational Genomics
RWTH Aachen University
Pauwelsstrasse 19
52074 Aachen, Germany
