### ISSUE TITLE
setupGenomicData.py error

### ISSUE THREAD

**Issue by Rayko87** [CostaLab/reg-gen#133]
Hello all,

I installed the RGT toolbox, but when I tried to download the genomic data using python setupGenomicData.py --hg19 I had this error:

Traceback (most recent call last):
  File "setupGenomicData.py", line 113, in <module>
    chr_list = ["chr" + str(e) for e in range(1, 23) + ["X", "Y", "M"]]
TypeError: unsupported operand type(s) for +: 'range' and 'list'

However, python setupGenomicData.py -h works perfectly. 

Is there a problem in the installation?

**Comment by fabio-t** [comment]
You should use Python 2 for RGT, as we still don't support Python 3.
