### ISSUE TITLE
Error: python setup.py install --user

### ISSUE THREAD

**Issue by umasstr** [CostaLab/reg-gen#134]
Update: After manually installing matplotlib, a new error populates:

    RuntimeError: implement_array_function method already has a docstring

setup.py exits with the below error:
     error: Setup script exited with
     Beginning with Matplotlib 3.1, Python 3.6 or above is required.
     This may be due to an out of date pip.
     Make sure you have pip >= 9.0.1

This is the version info on my end:

$ python3
Python 3.6.8 (default, Aug 20 2019, 17:12:48)

$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

**Comment by lzj1769** [comment]
Hi @umasstr ,

RGT currently does not support python3.
Can you try to install it with python2?

Best,
Li

**Comment by umasstr** [comment]
Hi Li,

I get the below error with a python2 install:

RuntimeError: Scikit-learn requires Python 3.5 or later. The current Python version is 2.7.15+ installed in /usr/bin/python2.

**Comment by fabio-t** [comment]
@umasstr Seems like scikit-learn has stopped supporting Python 2. My suggestion is that you make a `virtualenv` for python 2, and install there scikit-learn version 0.20.4 (the latest to support Python 2).

RGT will be converted to Python 3 in a few months, so the above is the only viable solution for the time being.
