### ISSUE TITLE
Error ( TypeError: expected c_int instead of c_int_Array_7865)

### ISSUE THREAD

**Issue by Saelm87** [CostaLab/reg-gen#136]
Hello,

While I am trying to analyze my ATAC data, I get this error which I don't know how to fix. 
I ran this code on the atac test data using this command:

`rgt-hint footprinting --atac-seq ATAC.bam ATACPeaks.bed`

However, I still get this error:

`Traceback (most recent call last):
  File "/home/sael/.pyenv/versions/2.7.0/bin/rgt-hint", line 10, in <module>
    sys.exit(main())
  File "/home/sael/.pyenv/versions/2.7.0/lib/python2.7/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/home/sael/.pyenv/versions/2.7.0/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 110, in footprinting_run
    atac_seq(args)
  File "/home/sael/.pyenv/versions/2.7.0/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 394, in atac_seq
    output_prefix=args.output_prefix)
  File "/home/sael/.pyenv/versions/2.7.0/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 807, in post_processing
    footprints_overlap = footprints.intersect(original_regions, mode=OverlapType.ORIGINAL)
  File "/home/sael/.pyenv/versions/2.7.0/lib/python2.7/site-packages/rgt/GenomicRegionSet.py", line 731, in intersect
    return self.intersect_c(y, mode, rm_duplicates)
  File "/home/sael/.pyenv/versions/2.7.0/lib/python2.7/site-packages/rgt/GenomicRegionSet.py", line 938, in intersect_c
    indices_c = POINTER(c_int)((c_int * max_len_result)())
TypeError: expected c_int instead of c_int_Array_7865`

Please could you tell me how to fix this issue.

Python = 2.7.0
HINT - Regulatory Analysis Toolbox (RGT) - v0.12.3

Thank you so much!

Sael

**Comment by lzj1769** [comment]
Hi,

Are you able to run the tutorial?
From the error message, footprinting is done successfully, but there is something with post-processing.

Is it possible to share your data with me? so I can try to figure out where it failed.

Best,
Li

**Comment by Saelm87** [comment]
Hi Li,
I tried to download the genome mm9 to run the tutorial using this command: 
`python setupGenomicData.py --mm9`

however it did not work, I got the following error:

`Traceback (most recent call last):
  File "setupGenomicData.py", line 222, in <module>
    chr_list = ["chr" + str(e) for e in range(1, 20) + ["X", "Y", "M"]]
TypeError: unsupported operand type(s) for +: 'range' and 'list'`

I then tried to download mm10 to run the tutorial with a different genome (I know not suitable but just to check the tool is working) and I got this error:

`python setupGenomicData.py --mm10
Downloading mm10 genome
--2019-10-22 18:23:27--  ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M11/GRCm38.primary_assembly.genome.fa.gz
           => ‘/home/sael/rgtdata/mm10/GRCm38.primary_assembly.genome.fa.gz’
Resolving ftp.ebi.ac.uk (ftp.ebi.ac.uk)... 193.62.197.74
Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.197.74|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/databases/gencode/Gencode_mouse/release_M11 ... done.
==> SIZE GRCm38.primary_assembly.genome.fa.gz ... 773507376
==> PASV ... done.    ==> REST 2118200 ... done.    
==> RETR GRCm38.primary_assembly.genome.fa.gz ... done.
Length: 773507376 (738M), 771389176 (736M) remaining (unauthoritative)

GRCm38.primary_assembly.genome.fa.gz   100%[===========================================================================>] 737.67M  2.82MB/s    in 4m 19s  

2019-10-22 18:27:46 (2.85 MB/s) - ‘/home/sael/rgtdata/mm10/GRCm38.primary_assembly.genome.fa.gz’ saved [773507376]

Traceback (most recent call last):
  File "setupGenomicData.py", line 282, in <module>
    output_genome_file.write(gz_file.read())
TypeError: write() argument must be str, not bytes`

The same is also applied to hg19.

I was able to download hg38 without errors 

Looking forward to your reply!

Best,
Sael

**Comment by mubadav** [comment]
I am getting a similar error and this is while running the example in the tutorial together with the sample dataset provided. 

> Hello,
> 
> While I am trying to analyze my ATAC data, I get this error which I don't know how to fix.
> I ran this code on the atac test data using this command:
> 
> `rgt-hint footprinting --atac-seq ATAC.bam ATACPeaks.bed`
> 
> However, I still get this error:
> 
> `Traceback (most recent call last): File "/home/sael/.pyenv/versions/2.7.0/bin/rgt-hint", line 10, in <module> sys.exit(main()) File "/home/sael/.pyenv/versions/2.7.0/lib/python2.7/site-packages/rgt/HINT/Main.py", line 95, in main args.func(args) File "/home/sael/.pyenv/versions/2.7.0/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 110, in footprinting_run atac_seq(args) File "/home/sael/.pyenv/versions/2.7.0/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 394, in atac_seq output_prefix=args.output_prefix) File "/home/sael/.pyenv/versions/2.7.0/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 807, in post_processing footprints_overlap = footprints.intersect(original_regions, mode=OverlapType.ORIGINAL) File "/home/sael/.pyenv/versions/2.7.0/lib/python2.7/site-packages/rgt/GenomicRegionSet.py", line 731, in intersect return self.intersect_c(y, mode, rm_duplicates) File "/home/sael/.pyenv/versions/2.7.0/lib/python2.7/site-packages/rgt/GenomicRegionSet.py", line 938, in intersect_c indices_c = POINTER(c_int)((c_int * max_len_result)()) TypeError: expected c_int instead of c_int_Array_7865`
> 
> Please could you tell me how to fix this issue.
> 
> Python = 2.7.0
> HINT - Regulatory Analysis Toolbox (RGT) - v0.12.3
> 
> Thank you so much!
> 
> Sael

**Comment by fabio-t** [comment]
@mubadav and @Saelm87, that "c_int_Array_7865" error is quite strange. We are currently in the process of converting RGT to Python 3. When that is ready, maybe you could try again and see if it's still there.

In the meanwhile, could you tell us your operating system?

**Comment by mubadav** [comment]
Hi @fabio-t, I am using Centos Linux version 2.6.32-358.el6.x86_64

**Comment by fabio-t** [comment]
@mubadav so I assume you also have Python 2.7.0. It may be worth a try to update it to the latest 2.7 version, if you can. There might have been some different behaviour in how `ctypes` worked.

**Comment by mubadav** [comment]
@fabio-t yes I do have the latest version of python 2.7

**Comment by fabio-t** [comment]
Can you give us the result of this command: `cat /etc/centos-release`

And also the full output when running the tutorial? Not only the traceback, but the full one start to finish.

**Comment by mubadav** [comment]
@fabio-t see the output below;

_% cat /etc/centos-release_
CentOS release 6.4 (Final)


This is the command I used to run the tutorial example

% _rgt-hint footprinting --atac-seq ATAC.bam ATACPeaks.bed_

And the only output I got was this traceback below

_Traceback (most recent call last):
  File "~/myenv/bin/rgt-hint", line 8, in <module>
    sys.exit(main())
  File "~/myenv/lib/python2.7/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "~/myenv/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 110, in footprinting_run
    atac_seq(args)
  File "~myenv/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 394, in atac_seq
    output_prefix=args.output_prefix)
  File "~/myenv/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line 807, in post_processing
    footprints_overlap = footprints.intersect(original_regions, mode=OverlapType.ORIGINAL)
  File "~/myenv/lib/python2.7/site-packages/rgt/GenomicRegionSet.py", line 731, in intersect
    return self.intersect_c(y, mode, rm_duplicates)
  File "~/myenv/lib/python2.7/site-packages/rgt/GenomicRegionSet.py", line 938, in intersect_c
    indices_c = POINTER(c_int)((c_int * max_len_result)())
TypeError: expected c_int instead of c_int_Array_7865_

**Comment by fabio-t** [comment]
Thanks. What about `python --version`?

**Comment by mubadav** [comment]
Looks like the default python on the server was Python 2.7.0, I switched to 2.7.14 and I managed to run the example successfully without getting the error

**Comment by fabio-t** [comment]
I'm glad the assumption was correct ;)

**Comment by fabio-t** [comment]
@Saelm87 that would solve it for you too - I'm closing this issue.
