### ISSUE TITLE
Installing development version of rgt get's utf error

### ISSUE THREAD

**Issue by kyliao** [CostaLab/reg-gen#144]
Hi, I'm trying to install development version of rgt to not get error while running python3.7 setup.py install --user

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 25: invalid start byte in scripts/bedGraphToBigWig file`

How can I fix this and install rgt properly?
Thank you

**Comment by fabio-t** [comment]
Hi, that is not the recommended way of installing RGT. Have you tried installing the latest release?

`pip install --user rgt`

**Comment by EricDeveaud** [comment]
Hello 

FYI UnicodeDecodeError is due to setuptools trying to get scrip_name from provided binaries in data/bin/[mac|linux]
