### ISSUE TITLE
No output for step 1 (target promoters) with customized rgtdata folder

### ISSUE THREAD

**Issue by caterinar** [CostaLab/reg-gen#145]
Hi!
We are trying to run rgt-tdf promotertest for customized data for Chinese hamster (scaffold level assembly).
Our input files include:
- Target gene list from differential expression analysis
- Fasta file for an lncRNA of interest
- rgtdata created from ENSEMBL version
However, gencode file is same as Refseq file with score replaced from “.” to “0”

We get the output if we run the same input (our gene list and our lncRNA.fa )with mm9 but for our data (CriGriPICR):

1. If we use rgtdata created with RefSeq version there is no output at all:

 ```
************** Promoter Test ***************
*** Input RNA sequence: /home/hdhiman/rgtdata/lncRNA.fa

*** Output directory: rgtdata/promoter_test_crigri/lnc_name

Step 1: Calculate the triplex forming sites on RNA and DNA.

Dump to file: tdf.dump.crigri.gene_list2

Running time: 0:01:17

Step 2: Calculate the frequency of DNA binding sites within the promoters.

Counting frequency of promoters on DBD...

0	Binding target promoters

0	Binding non-target promoters

Counting frequency of binding sites on DBD...

0	Binding sites on de promoters

Running time: 0:00:00

Step 3: Generate plot and output html files.

*** Find no DBD having DBS with cutoff = 0.1

Running time: 0:00:00

Total running time: 0:01:17
```

2. With ENSEMBL version of the customized rgtdata we figured out that nontarget_promoters.tpx was able to run successfully but not target_promoters.tpx.

```
**~/rgtdata$ rgt-TDF promotertest -r lncRNA.fa -de gene_list2.txt -organism CriGriPICR -rn lnc_name -o promoter_test_CriGriPICR -l 20**


************** Promoter Test ***************

*** Input RNA sequence: /home/hdhiman/rgtdata/lncRNA.fa

*** Output directory: rgtdata/promoter_test_CriGriPICR/lnc_name

Step 1: Calculate the triplex forming sites on RNA and DNA.

Dump to file: tdf.dump.CriGriPICR.gene_list2

Running time: 0:09:27

Step 2: Calculate the frequency of DNA binding sites within the promoters.

Counting frequency of promoters on DBD...

0	Binding target promoters

Traceback (most recent call last):

  File "/home/hdhiman/.local/bin/rgt-TDF", line 8, in <module>

    sys.exit(main())

  File "/home/hdhiman/.local/lib/python3.6/site-packages/rgt/tdf/Main.py", line 357, in main

    file_tpx_de=tpx_de, file_tpx_nde=tpx_nde)

  File "/home/hdhiman/.local/lib/python3.6/site-packages/rgt/tdf/Statistics.py", line 79, in count_frequency_promoters

    self.tpx_nde.read_tpx(file_tpx_nde, dna_fine_posi=False)

  File "/home/hdhiman/.local/lib/python3.6/site-packages/rgt/tdf/RNADNABindingSet.py", line 586, in read_tpx

    dna = GenomicRegion(chrom=l[3].split(":")[0], initial=int(rg[0]), final=int(rg[1]),

ValueError: invalid literal for int() with base 10: ‘'
```

Since we are using RefSeq version for the rest of the analysis, can you kindly let me know if the tool requires ENSEMBL version specifically?

If yes, then what could be the problem when our lists are ENSEMBL based but Step 2 still gives an  error?

We can share the customized data folder that we created, if required

Thanks !!

**Comment by fabio-t** [comment]
Yes, it would be great if you could share you RGTDATA folder.

**Comment by caterinar** [comment]
Is there a way to send them privately? Moreover, they are heavy even if
compressed and I don't manage to share them in the comment.
>>> Fabio Ticconi <notifications@github.com> 4/22/2020 12:24 pm >>>
Yes, it would be great if you could share you RGTDATA folder.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(
https://github.com/CostaLab/reg-gen/issues/145#issuecomment-617691121) ,
or unsubscribe
(

**Comment by caterinar** [comment]
Hi!
Any update?

**Comment by fabio-t** [comment]
Hi, I'm downloading the data and will have a look this week. It might be as easy as a minor formatting issue with the data you used. We generally do not support errors with user-defined genomes but if it's simple enough, I'll provide a solution for you.

Can you also provide your `data.config` and data.config.user` files?

**Comment by caterinar** [comment]
I added them in the same box. The paths/to/file_name in the data.config and data.config.user do not correspond to the names of the files that I provided as they are other versions of the annotations. Anyways, when I set the data.config and data.config.user files, I used the correct path to the RGTDATA folder that I wanted.

**Comment by fabio-t** [comment]
Seems like I cannot download the file, maybe some temporary issue with bokubox. Will try again..
