### ISSUE TITLE
RGT-Hint footprint cut count score confusion

### ISSUE THREAD

**Issue by davemcg** [CostaLab/reg-gen#148]
Why do I have negative numeric values (as low at -40.3) at this column? Is there some kind of scaling applied? I was expecting integers. And certainly nothing negative.

Running footprinting as follows (0.12.3):

rgt-hint footprinting \
            --atac-seq \
            --paired-end \
            --organism=hg38 \
            --output-prefix {wildcards.sample} \
            --output-location=bulkATAC/HINT \
            {input.bam} \
            {input.peaks}

**Comment by lzj1769** [comment]
hi,

the latest version of RGT is 0.13.0, can you try it and see this fixes the issue?

Best,
LI

**Comment by fabio-t** [comment]
Assuming the issue was fixed, closing here.
