### ISSUE TITLE
rgt-hint differential failing - low # of peaks

### ISSUE THREAD

**Issue by ammawla** [CostaLab/reg-gen#149]
I'm wondering if there's a workaround when dealing with a low # of peaks. The tool works great normally, but if I evaluate a specific subset of ATAC peaks (~600 in total) that are relevant to the question I'm asking, the analysis fails at the last step, unable to assign a differential factor value to the groups. 

I understand that one pitfall would be a loss of resolution and statistical power, but I was wondering if there's a tweak to this in order to get an initial set of results? 

Thank you very much.

**Comment by lzj1769** [comment]
Hi

One approach will be using a high fdr for motif matching so you can get more TF binding sites. rgt-hint needs enough ATAC-seq signal to first generate a footprint-like line plot for each motif and then compute the activity score. If the signal is too weak, the activity score will be failed for all motifs, and computing a normalization factor will not be possible.

Best,
Li
