### ISSUE TITLE
lack of mm10 annotation files

### ISSUE THREAD

**Issue by xflicsu** [CostaLab/reg-gen#15]
Hello, I want to predict binding sites of lncRNA with mm10 genome.
And it is lack of mm10 annotation files in this package.
So, could you attach those files in new version?
Thanks!

**Comment by jovesus** [comment]
Hi Xianfeng,

Thank your for your asking. Yes, we are going to do an update recently
including the annotation for mm10.

best,

*Joseph Kuo (Chao-Chung Kuo)*

**Comment by xflicsu** [comment]
Thanks
