### ISSUE TITLE
rgt-hint differential error

### ISSUE THREAD

**Issue by Arkosen** [CostaLab/reg-gen#151]
I have tried to run rgt-hint differential for a while and continue to get this error. Does anyone have a solution?

(rgt) bash-4.1$ # perform differential analysis
(rgt) bash-4.1$ rgt-hint differential --organism=hg38 --output-profiles --bc --nc 12 --mpbs-files=$mpbs --reads-files=$bam --conditions=$cond --output-location=$outdir
generating signal for each motif and condition...

signal generation is done!
generating line plot for each motif...

Traceback (most recent call last):
  File "/iblm/netapp/home/asen/myconda/envs/rgt/bin/rgt-hint", line 11, in <module>
    sys.exit(main())
  File "/iblm/netapp/home/asen/myconda/envs/rgt/lib/python2.7/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/iblm/netapp/home/asen/myconda/envs/rgt/lib/python2.7/site-packages/rgt/HINT/DifferentialAnalysis.py", line 234, in diff_analysis_run
    pool.map(output_line_plot, arguments_list)
  File "/iblm/netapp/home/asen/myconda/envs/rgt/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/iblm/netapp/home/asen/myconda/envs/rgt/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
IndexError: list index out of range

**Comment by lzj1769** [comment]
hi @Arkosen 

can you provide more information about how you ran rgt-hint diff?
for example, 
the version of rgt
how many conditions did you input?

this error message means there is something wrong when rgt-hint tries to generate the line plot.
but the signal generation is ok.

Best,
Li

**Comment by Arkosen** [comment]
Hi Li
Thank you for your prompt reply.
1. version number  v0.12.3
2. I am running 30 samples split unevenly into 10 conditions (some groups may be represented by 1 sample)
do you need more info.
Thanks

**Comment by lzj1769** [comment]
Hi @Arkosen 

the latest version is v0.13.0
can you try to upgrade your rgt and see if the problem is solved?

Best,
Li

**Comment by Arkosen** [comment]
Could you sent me link to the newest version. The website "http://www.regulatory-genomics.org/hint/introduction/" states v0.12.3 is the latest version. Is your new version on conda?

**Comment by fabio-t** [comment]
@lzj1769 I suggest that we either use some trick to show the actual latest version, or that the website **doesn't** show any version number but at most links to the RGT release page here on Github.

@Arkosen the suggested way to install RGT is via pip, that would allow you to upgrade with the command `pip install --user rgt -U`. But you can also download it manually here: https://github.com/CostaLab/reg-gen/releases

**Comment by nfancy** [comment]
Hi, I am using the v0.13.1 but I have the same error and if I set --no-lineplots then I get the differential statistics but the p-values are nan. This is for a single gene, whereas with the exact same command it works for another gene

```
~/.local/bin/rgt-hint differential \
--organism=hg38_custom \
--bc --nc 10 \
--no-lineplots \
--mpbs-files=$output_dir/match_target/none/target_regions_mpbs.bed,$output_dir/match_target/IFNg/target_regions_mpbs.bed \
--reads-files=$input_dir/none.mRp.clN.sorted.bam,$input_dir/IFNg.mRp.clN.sorted.bam \
--conditions=Control,IFNg \
--output-location=$output_dir/rgt_de_cgas_ifng
```

Any pointers?

Nurun

**Comment by lzj1769** [comment]
Hi @nfancy ,

If I understand it correctly, you are only interested in this single gene, and your target regions are now genome-wide, right?

RGT-hint needs to compute a normalization factor for each condition, and the assumption behind this normalization is that the majority of TFs do not change, therefore they can be used to estimate the normalization factor. If the number of input regions is too low and there are no binding sites for many TFs, the assumption might be broken

Best,
Li
