### ISSUE TITLE
Warning rgt-hint "The scikit HMM encountered erros when applied in region (chr, , ). This iteration will be skipped"

### ISSUE THREAD

**Issue by Knetsy** [CostaLab/reg-gen#163]
Hello,
I have run rgt-hint on single cell ATAC-seq data following the [tutorial](https://www.regulatory-genomics.org/hint/tutorial-differential-footprints-on-scatac-seq/) that you provided and I got some 
[warnings](https://github.com/CostaLab/reg-gen/files/5217231/slurm-2018757.txt). I wanted to know if I can just ignore them?
This is the command that I have used `rgt-hint footprinting --atac-seq --paired-end --organism hg38 --output-location $HOME/Results/Footprints_scHINT/ --output-prefix scATAC_A1 ./A1.sort.bam ./A1.all.bed`

I am running HINT v0.13.1 running python 3.6.4.

Thanks!

Deborah

**Comment by lzj1769** [comment]
Hi Deborah,

> I wanted to know if I can just ignore them?

Yes, you can just ignore them. 
This error message means that the HMM model failed to segment the signal from these regions.
And this usually happens if the region is very close to the start or end of the chromosome.

best,
Li
