### ISSUE TITLE
Differential footprint NaN for y-axis limit

### ISSUE THREAD

**Issue by gartician** [CostaLab/reg-gen#164]
Hi RGT devs, thank you for your valuable bioinformatic contribution to the regulatory genetics space. This issue pertains to HINT-ATAC footprinting. 

김재훈 and I encountered this issue where the sequencing depth normalization factor returns NA. In my case, the error comes from the compute_factors() function (line 460 - 467, DifferentialAnalysis.py). Once the signal for a 200 bp window is summed row-wise, it is possible that in one condition, the summed value could be zero. And if you log zero, you'll get an NA.
It seems like the following line will remove some NA entries, but somehow doesn't work in practice. What I've done is add a "pseudo-signal" of 0.01, so from:

```python
def compute_factors(signals):
    signals = np.sum(signals, axis=2)
    signals_log = np.log(signals)
    ...
```

to this

```python
def compute_factors(signals):
    signals = np.sum(signals, axis=2)
    signals_log = np.log(signals + 0.01)
    ...
```

I'm not sure whether to keep or remove the following line that catches the NA or not, so that's up to the devs. 

[Original post](https://groups.google.com/g/rgtusers/c/H8AieNJMniM/m/U3pNqO3IAwAJ) in the RGT users Google group.

**Comment by lzj1769** [comment]
Hi @gartician ,

Thanks for your input.

```
def compute_factors(signals):
    signals = np.sum(signals, axis=2)
    signals_log = np.log(signals + 0.01)
    ...
```

This is a good solution. 
I have implemented it in develop branch and it helps us to get rid of NA value problem.

Best,
Li

**Comment by gartician** [comment]
Sorry I wasn't aware I could close the issue earlier. Glad to hear 👍
