### ISSUE TITLE
Using `rgt-hint differential` with replicates?

### ISSUE THREAD

**Issue by hoholee** [CostaLab/reg-gen#169]
Dear RGT dev team,

I was trying to run HINT-ATAC differential (rgt version v0.13.1) using replicates with a code snippet as follow:

```
rgt-hint differential --organism=hg19 --bc --nc 30 \
--mpbs-files=cond1_rep1_mpbs.bed,cond1_rep2_mpbs.bed,cond2_rep1_mpbs.bed,cond2_rep2_mpbs.bed \
--reads-files=cond1_rep1.bam,cond1_rep2.bam,cond2_rep1.bam,cond2_rep2.bam \
--condition=cond1,cond1,cond2,cond2 \
...
```
I was expecting to see some sort of average/median scores generated from the two replicate for each condition, but instead the `differential_statistics.txt` file gave four columns of protection score and four columns of tag count (with identical colnames like `TC_cond1, TC_cond1, TC_cond2, TC_cond2`). Also the `TF_Activity`, `Z_score`, `P_values` columns are missing.

Could you elaborate on how you perform the differential test and compute these three metrics? I couldn't find this on the manual but I'm guessing `TF_Activity` is the `∆ACT(TF)` in the method section of your paper(https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1642-2#Sec13)? But I'm still not sure how you get the Z and P. Is it possible to tweak the code to run the test using the replicates?

Thanks in advance!

Best,
Junhao.

**Comment by lzj1769** [comment]
Hi,

rgt-hint differential was initially designed for comparing two conditions with TF activity, which is sum of Protection_Score and TC.
For more than two conditions, it will not compute TF activity.
In your case, you can use this table to compute TC activity and do some tests.

best,
Li
