### ISSUE TITLE
Fix MacOS support

### ISSUE THREAD

**Issue by fabio-t** [CostaLab/reg-gen#17]
It's almost done, but there's still some weirdness. Must try it in a few more macs.

**Comment by fabioticconi** [comment]
Current issues: the following dependency formatting doesn't work for some (it worked for joseph, and in a clean virtual environment):

```
ngslib;platform_system=='Linux'
```

It either tries to compile it, and fails of course, or it crashes on ```pip setup.py egg_info```. @jovesus can you paste the error message here?

**Comment by fabioticconi** [comment]
Right now, if the user first installs python via Homebrew, there shouldn't be problems. Hopefully.

```
brew install python
pip install rgt --user
```

More testing needs to be done.

**Comment by fabioticconi** [comment]
Pysam caused MacOS regressions in the last few versions. While waiting for the fix, we've had to block the pysam dependency to version 1.11.1.

**Comment by fabioticconi** [comment]
Triplexes is not compiled for Mac. @jovesus could you have a look at that (when you are back)?

**Comment by zjin1126** [comment]
SeqAn C++ template is not compatible with LLVM libc++, which used by clang in default settings.
Compile Triplexes with GNU libstdc++ can bypass this problem.

Build Triplexes without OpenMP:
```
SRC_ROOT=/path/to/triplexes

cmake $SRC_ROOT \
-DCMAKE_CXX_FLAGS="-stdlib=libstdc++" \
-DCMAKE_BUILD_TYPE=Release \
-DSHAREDLIBRARY=TRUE

make
```
Pre-installed clang on macOS doesn't support OpenMP, so install clang via Homebrew.
Build Triplexes with OpenMP:
```
brew install llvm # clang with openmp support

export CC=/usr/local/opt/llvm/bin/clang
export CXX=/usr/local/opt/llvm/bin/clang++

cmake $SRC_ROOT \
-DCMAKE_CXX_FLAGS="-I/usr/local/opt/llvm/include -stdlib=libstdc++" \
-DCMAKE_C_FLAGS="-I/usr/local/opt/llvm/include" \
-DCMAKE_SHARED_LINKER_FLAGS="-L/usr/local/opt/llvm/lib" \
-DOpenMP_C_FLAGS="-fopenmp" \
-DOpenMP_CXX_FLAGS="-fopenmp" \
-DCMAKE_BUILD_TYPE=Release \
-DSHAREDLIBRARY=TRUE

make
```
These `cmake` options can let `rgt-TDF` run on macOS.

After compile, copy libtriplexator.dylib to rgtdata/lib and modify `path_triplexator` in data.config to `path_triplexator=$HOME/rgtdata/lib/libtriplexator.dylib`.

**Comment by fabioticconi** [comment]
@zjin1126 this is VERY helpful! Thanks. We will give this a try soon.

**Comment by jovesus** [comment]
@zjin1126 Thank you for your contribution. Last week I tried to install openMP on mac and use llvm to compile, but because of not having sufficient understanding of cmake, I couldn't work it out. Your comment solves our problem exactly. Thank you.

Now if RGT is successfully installed on Mac, it works as nrmal as on Linux.

**Comment by fabio-t** [comment]
I'm fairly sure now RGT works fine on Mac. We'll open specific issues in the future, in case of need.
