### ISSUE TITLE
can't connect to ftp.ebi.ac.uk 

### ISSUE THREAD

**Issue by Rapunzel12138** [CostaLab/reg-gen#173]
Hello,
I'm trying to download the genomic data ,but I can't connect to the website by typing 'python setupGenomicData.py --mm10'.   I just wonder if the website 'ftp.ebi.ac.uk' works fine. And if not, is there any other way to fetch the genomic data?
     
**Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.197.74|:21... failed: Connection timed out.**

Any advice as to how to work around this would be greatly appreciated. 

Thanks,

Rapunzel

**Comment by jovesus** [comment]
Hi,

Before we fix it in the code accordingly, you can just download the FASTA
file by the link below:
ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/GRCm38.primary_assembly.genome.fa.gz

Thank you for reporting it.


Am So., 20. Dez. 2020 um 16:37 Uhr schrieb Rapunzel12138 <
notifications@github.com>:
