### ISSUE TITLE
rgt-TDF regiontest is throwing import error for matplotlib

### ISSUE THREAD

**Issue by ranijames** [CostaLab/reg-gen#174]
Hi All,
I am using rgt-TDF for finding the genomic binding sites. As a test run when I started with `rgt-TDF regiontest` it is throwing me the following error,

```
Traceback (most recent call last):
 File "/home/alva/.local/bin/rgt-TDF", line 5, in <module>
   from rgt.tdf.Main import main
  File "/home/alva/.local/lib/python3.7/site-packages/rgt/tdf/Main.py", line 19, in <module>
   from .triplexTools import get_dbss, check_dir,run_triplexator, run_triplexes, \
  File "/home/alva/.local/lib/python3.7/site-packages/rgt/tdf/triplexTools.py", line 17, in <module>
  from matplotlib import colors
ImportError: cannot import name 'colors' from 'matplotlib' (unknown location)

```
I am running on Ubuntu 18 and in Python 3.7.3 version.

Besides that, I have one more question does the tool predict potential triple helix binding regions for a given list of lncRNAs within from RNA sequences and in the provided list of chromosomal coordinates? 
For instance, I have 10 lncRNAs and the corresponding RNA sequences of those lncRNAs. Additionally, I have a list of genomic regions in BED format.
Thanks

**Comment by jovesus** [comment]
Hi,

Can you let us know which version of matplotlib you are using?

The answer to your question at the end is yet. TDF is able to analyse the
binding potential of a list of lncRNAs against a list of genomic regions.

*Joseph Chao-Chung Kuo*


Am Do., 21. Jan. 2021 um 17:03 Uhr schrieb Alva Rani James <
notifications@github.com>:

**Comment by ranijames** [comment]
@jovesus Thanks for the reply.
The matplotlib   version I am using is:           `  3.2.1                    pypi_0    pypi`

**Comment by jovesus** [comment]
Sorry, I am not able to replicate your problem. I have tried to install RGT
via pip freshly in a virtual machine and it works fine. I will recommend
you to reinstall matplotlib. I think it may be an installation issue in
matplotlib.

Please let me know if you need further assistance.

*Joseph Chao-Chung Kuo*


Am Sa., 23. Jan. 2021 um 15:56 Uhr schrieb Alva Rani James <
notifications@github.com>:

**Comment by ranijames** [comment]
@jovesus Thanks for your time !
So now I have created conda virtual environment on python 3.7.3. 
 `conda create -n tdf python=3.7.3 anaconda`
Then, I have been trying to install the `rgt` as recommended [http://www.regulatory-genomics.org/rgt/download-installation/](here).

Which is throwing the following error,
```
Using cached mpmath-1.1.0.tar.gz (512 kB)                                                                                                                e)
Collecting HTSeq                                                                                                                                           │ a
  Using cached HTSeq-0.13.5.tar.gz (318 kB)                                                                                                                lv
    ERROR: Command errored out with exit status 1:                                                                                                         a@
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ApyFr0/htseq/setup.py'"'"'; __file__='"'"'/tmp/pip-│al
install-ApyFr0/htseq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(c│va
ompile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fKkyWe                                                                  -X
         cwd: /tmp/pip-install-ApyFr0/htseq/                                                                                                               PS
    Complete output (2 lines):                                                                                                                             -1
    Error in setup script for HTSeq:                                                                                                                       3-
    HTSeq requires Python 3.5+.                                                                                                                            93
    ----------------------------------------                                                                                                               │70
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.   
```       
 Besides that, I have also tried using `pip install --user RGT`, which also ended up throwing the same error as mentioned above.

**Comment by jovesus** [comment]
Hi, I did pip3 install on a new virtual environment and it works fine. Your error message in conda shows some comflict...
If you indeed install by Python 3.7.3, why it reports the error about `HTSeq requires Python 3.5+`? Sorry, I am not familiar with conda and I didn't check it yet.

Could you install it again with pip3 instead of pip?

**Comment by ranijames** [comment]
Thank you @jovesus  for the support. I have completely deleted all installations of `rgt` from my computer. And then cloned the Github repo (although it's not recommended), and followed the setup rules. Currently, I have installed the package and it is running without any issues.

I appreciate your time and patience!

**Comment by jovesus** [comment]
You are welcome.
