### ISSUE TITLE
Error using rgt-TDF get_TTS

### ISSUE THREAD

**Issue by chiaracicco** [CostaLab/reg-gen#175]
Hi,
I'm trying to run rgt-TDF get_TTS with an RNA fasta file and a ChIRP.bed file from a ChIRP experiment (I use RGT-0.13.1).

When using the first 10 lines of the bed file (head -n 10 ChIRP.bed > pippo.bed) I am able to obtain the expected output without errors.
```
rgt-TDF get_TTS -r lncRNASmad7.fa -i pippo.bed -organism mm10
```

When using the entire bed file or even the first 1000 lines of the bed file (head -n 1000 ChIRP.bed > pippo2.bed) instead, I got this error message:

```
rgt-TDF get_TTS -r lncRNASmad7.fa -i pippo2.bed -organism mm10

Total binding events:    2441
Traceback (most recent call last):
  File "/usr/local/bin/rgt-TDF", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/rgt/tdf/Main.py", line 262, in main
    fr=args.fr,fm=args.fm,of=args.of,mf=args.mf,rm=args.rm,temp=current_dir)
  File "/usr/local/lib/python3.7/dist-packages/rgt/tdf/triplexTools.py", line 898, in get_dbss
    txp.write_bed(output_BED)
  File "/usr/local/lib/python3.7/dist-packages/rgt/tdf/RNADNABindingSet.py", line 673, in write_bed
    dbss.write(filename)
  File "/usr/local/lib/python3.7/dist-packages/rgt/GenomicRegionSet.py", line 257, in write
    io.write_from_grs(self, filename, mode)
  File "/usr/local/lib/python3.7/dist-packages/rgt/GenomicRegionSet.py", line 94, in write_from_grs
    with open(filename, mode) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Any advice as how to work around this would be greatly appreciated.

Best, Chiara

**Comment by jovesus** [comment]
Hi,

Please try to add `-tts` in your command to specify the output file:
`rgt-TDF get_TTS -r lncRNASmad7.fa -i pippo2.bed -organism mm10 -tts TTS.bed`

-tts          Output BED file of the TTSs

Let me know what you get. Best.

**Comment by chiaracicco** [comment]
Thank you for your fast reply @jovesus, it worked.

The point is, I was primarily trying to figure out if triplex identification may be the failure point in the execution of the regiontest.

In fact, running:
```
rgt-TDF regiontest -r lncRNASmad7.fa -bed pippo.bed -rn lncRNASmad7 -organism mm10 -o TDF_pippo -n 1000 -mp 10

*************** Genomic Region Test ***************
*** Input RNA sequence: lncRNASmad7.fa
*** Input regions in BED: pippo.bed
*** Number of randomization: 1000
*** Output directory: lncRNASmad7
Step 1: Calculate the triplex forming sites on RNA and DNA.
        Running time: 0:00:01
Step 2: Permutation by randomization the target regions for 1000 times.
                |0%                  |                100%|
                [=========================================]
        Running time: 0:00:25
Step 3: Generate plot and output html files.
        Running time: 0:00:01

Total running time: 0:00:27
```

Meanwhile, running: 
```
rgt-TDF regiontest -r lncRNASmad7.fa -bed pippo2.bed -rn lncRNASmad7 -organism mm10 -o TDF_pippo2 -n 1000 -mp 10

*************** Genomic Region Test ***************
*** Input RNA sequence: lncRNASmad7.fa
*** Input regions in BED: pippo2.bed
*** Number of randomization: 1000
*** Output directory: lncRNASmad7
Step 1: Calculate the triplex forming sites on RNA and DNA.
        Running time: 0:00:12
Step 2: Permutation by randomization the target regions for 1000 times.
*** Find no DBD having DBS with cutoff = 0.1
```
If you have any suggestions I would really appreciate it.

Best, Chiara

**Comment by jovesus** [comment]
Hi Chiara,

There is a parameter for this:
`-ccf          Define the cut off of triplex-forming regions per DBD in percentage of total triplexes (0-1) or an integer. (default: 0.1)`

This parameter defines the minimal number of TFO within a DBD. If it is very few, the program will ignore it.
ccf>1: You define the exact number of TFOs you want, such as 10
ccf<1: You define the percentage of TFOs out of all detected TFOs for each DBD. The default is 0.1. It means that for each output DBD, there are at least 10% of TFOs included.

In your case, when you limit only the first 1000 lines, those regions don't generate enough triplexes under this setup. You can even try `-ccf 1` to see what the result is.

**Comment by chiaracicco** [comment]
Thank you @jovesus for your help and your work!
