### ISSUE TITLE
0 motifs loaded

### ISSUE THREAD

**Issue by RadPa** [CostaLab/reg-gen#179]
Hi,
I am working on insect data, as suggested by earlier posts, I used createPwm.py to create jaspar_insect. But when I run the motifanalysis-matching does not load motifs (0 motifs). Apart from default jaspar_vertebrate, no other load the motifs.
Can you please help, I do not know what's wrong, is my data or the way I am analyzing it.
RGT-HINT v0.13.1
python3.7
python3 createPwm.py -i JASPAR2020_CORE_insects_non-redundant_pfms_jaspar.txt -f jaspar-2016 -o jaspar_insect
rgt-motifanalysis matching --motif-db jaspar_insect --organism ins --input-files at1.bed an1.bed at2.bed an2.bed
>> genome: ins
>> pseudocounts: 1.0
>> fpr threshold: 0.0001

>> loading input files..
>>> at1, 357224 regions
>>> an1, 333812 regions
>>> at2, 395054 regions
>>> an2, 317038 regions

>> loading external motif databases..
>>> jaspar_insect

>> motifs loaded: 0

>> matching [at1], 357224 regions... [8.620 seconds]
>> matching [an1], 333812 regions... [8.857 seconds]
>> matching [at2], 395054 regions... [10.146 seconds]
>> matching [an2], 317038 regions... [8.291 seconds]

**Comment by fabio-t** [comment]
Small typo in the arguments, try with `--motif-dbs`

**Comment by RadPa** [comment]
I tried --motif-dbs, still, 0 motifs loaded.

**Comment by fabio-t** [comment]
OK, I'll try to replicate it and get back to you.

**Comment by RadPa** [comment]
Hi,
One of the older posts helped in solving the issue.
I changed jaspar_insect to jasper-insect, and it worked.
Sorry for the inconvenience.
Thank you.

**Comment by RadPa** [comment]
Except for default jaspar_vertebrate, other databases do not load the motifs.
rgt-motifanalysis matching --motif-dbs uniprobe_primary --organism ins --input-files at1.bed an1.bed at2.bed an2.bed

**Comment by fabio-t** [comment]
Hi @RadPa, the option `--motif-dbs` is used for the quick & dirty loading of external motif databases, like the one you created. If you don't have a directory called `uniprobe_primary` where you type that command, it won't work the way you think.

For example, assuming you have a default rgtdata path, try this: `--motif-dbs ~/rgtdata/motifs/uniprobe_primary`

With reference to `jaspar-insect`, to be honest, the underscore should not matter at all. So it probably wasn't that the issue.

You should read this page, specifically the section "Hard way": https://www.regulatory-genomics.org/motif-analysis/additional-motif-data/

It will teach you how to setup jaspar insects with metadata, and how to add it to `data.config.user` to the list of your repositories. You can then use the filter option (read the documentation to see how it works) to use insect or other dbs for specific experiments.

**Comment by fabio-t** [comment]
Please reopen this if something still not working or clear. Closing for now.

**Comment by RadPa** [comment]
Thank you for the mail and clarification.
I will read the section you have mentioned, and if I reencounter the issue,
I will reopen the issue.
I apologize for the delayed mail.

Good Day
Radhika
