### ISSUE TITLE
Add arabdopsis genome

### ISSUE THREAD

**Issue by fabio-t** [CostaLab/reg-gen#183]

**Comment by ydy1127** [comment]
Hi，

I tried to install RGT today, but did not find any data related to arabidopsis genome. May I ask how to add arabidopsis genome.

Looking forward to your reply.

**Comment by lzj1769** [comment]
Hi, 

I am not familiar with arabidopsis? Do you mean the genome from here: https://www.arabidopsis.org/portals/genAnnotation/gene_structural_annotation/agicomplete.jsp?

If this is the case, I can try to add it to our script, so you can set it up by running:
python setupGenomicData.py --tair10

**Comment by lzj1769** [comment]
Update:

I have added the arabidopsis genome to develop branch, the genome is found here:
https://plants.ensembl.org/info/data/ftp/index.html

can you install the rgt from develop branch and try it with your data?

To use it, you need to run the following commands:

```
git clone git@github.com:CostaLab/reg-gen.git
cd reg-gen
git checkout develop
pip install ./
``` 
then go to directory ~/rgtdata  and install tair10 data by
`python setupGenomicData.py --tair10`

After that, you should be able to use the tair10 genome.

Best,
Li

**Comment by ydy1127** [comment]
Hi，

Thanks for your apply! I reinstalled reg-gen as you suggested and successfully configured the TAIR10 genome by running the code.

Then, the _tair10_ folder already exists under the _rgData_ folder. However, when I run "rgt-hint footprinting", I get the following error message:

`Traceback (most recent call last):
  File "/home/yuandy/anaconda3/lib/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/home/yuandy/anaconda3/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/yuandy/anaconda3/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'gene_regions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuandy/anaconda3/bin/rgt-hint", line 8, in <module>
    sys.exit(main())
  File "/home/yuandy/anaconda3/lib/python3.8/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/home/yuandy/anaconda3/lib/python3.8/site-packages/rgt/HINT/Footprinting.py", line 110, in footprinting_run
    atac_seq(args)
  File "/home/yuandy/anaconda3/lib/python3.8/site-packages/rgt/HINT/Footprinting.py", line 134, in atac_seq
    genome_data = GenomeData(args.organism)
  File "/home/yuandy/anaconda3/lib/python3.8/site-packages/rgt/Util.py", line 93, in __init__
    self.gene_regions = os.path.join(self.data_dir, self.config.get(organism, 'gene_regions'))
  File "/home/yuandy/anaconda3/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'gene_regions' in section: 'tair10'`

When I checked the _data.config_ file in the _rgdata_ folder, I found that unlike other genomes, the configuration information of Tair10 does not contain the two terms "gene_regions" and "gene_alias", as follows:

`[zv10]
genome: zv10/genome_zv10_ensembl_release_84.fa
chromosome_sizes: zv10/chrom.sizes.zv10
gene_regions: zv10/genes_zv10.bed
annotation: zv10/Danio_rerio.GRCz10.84.gtf
gene_alias: zv10/alias_zebrafish.txt

[tair10]
genome: tair10/genome_tair10_ensembl_release_51.fa
chromosome_sizes: tair10/chrom.sizes.tair10
annotation: tair10/Arabidopsis_thaliana.TAIR10.51.gtf`

Tair10 genome does not seem to be configured successfully. Looking forward to your reply!

**Comment by lzj1769** [comment]
Hi,

Thanks for your feedback. 
I have added these two files to develop branch.
can you try it again?

Best,
Li

**Comment by ydy1127** [comment]
Hi，

Thanks for your apply! The program ran successfully！
