### ISSUE TITLE
why I can't download your example?

### ISSUE THREAD

**Issue by thekingofall** [CostaLab/reg-gen#184]
https://costalab.ukaachen.de/open_data/hint/tutorial/HINT_ATACTest.tar.gz

I had tried many times and still can't download the sample

**Comment by lzj1769** [comment]
Hi,

Our server is under upgrading, during which it's not accessible.
Can you try it again later?

Best,
Li

**Comment by thekingofall** [comment]
thank you very much



---Original---
From: "Zhijian ***@***.***&gt;
Date: Thu, May 13, 2021 17:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CostaLab/reg-gen] why I can't download your example? (#184)




 
Hi,
 
Our server is under upgrading, during which it's not accessible.
 Can you try it again later?
 
Best,
 Li

**Comment by lzj1769** [comment]
The server was back, and the link is working again, therefore this issue is closed.
