### ISSUE TITLE
how to deal with this error?

### ISSUE THREAD

**Issue by thekingofall** [CostaLab/reg-gen#185]
Program: rgt-hint.
Report: The scikit HMM encountered errors when applied. in region (Chr1,155168020,155168021). This iteration will be skipped.
--------------------------------------------------
--------------------------------------------------

I don't konw what happened?

**Comment by lzj1769** [comment]
Hi,

This message is saying the HMM cannot segment the signal, which was generated from the input region.
Because it's only 1 bp long.

You can ignore this.

Best,
Li
