### ISSUE TITLE
Unexpected output from the histone code?

### ISSUE THREAD

**Issue by tombartlett** [CostaLab/reg-gen#188]
I've run this on different systems (both a Mac OSX laptop, and a centrally-maintained UNIX cluster server) and am experiencing the same problem with RGT HINT footprinting. Specifically, it runs for around 90 mins, then produces an error like this:

Traceback (most recent call last):
  File "/home/ucbptba/.python3local/bin/rgt-hint", line 8, in <module>
    sys.exit(main())
  File "/home/ucbptba/.python3local/lib/python3.8/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/home/ucbptba/.python3local/lib/python3.8/site-packages/rgt/HINT/Footprinting.py", line 114, in footprinting_run
    histone(args)
  File "/home/ucbptba/.python3local/lib/python3.8/site-packages/rgt/HINT/Footprinting.py", line 647, in histone
    post_processing(footprints=footprints, original_regions=original_regions, fp_min_size=fp_min_size,
  File "/home/ucbptba/.python3local/lib/python3.8/site-packages/rgt/HINT/Footprinting.py", line 839, in post_processing
    p2 = min(mid + tc_ext, chrom_sizes_dict[f.chrom])
KeyError: '1'

The command I am using to run this processing is as follows:

rgt-hint footprinting --histone sample1.H3K4me3.filtered.sorted.dedup.bam sample1.H3K4me3_peaks.narrowPeak

Any advice how to resolve this would be very much appreciated!

**Comment by lzj1769** [comment]
Hi @tombartlett ,

What is your reference genome? is it mouse or human?
the defaulting setting is hg19, and probably you need to set --organism properly.


best,
Li

**Comment by tombartlett** [comment]
Hi,

Thanks very much for getting back to me!

I am using hg19 so this is correct (I am using human not mouse).

Thanks for any further help you can give,

Tom

________________________________

**Comment by lzj1769** [comment]
Hi,

Thanks for providing the infomation.

Can you try to run the test script here:
https://github.com/CostaLab/reg-gen/blob/master/test/hint.sh

This script will test the footprinting function of using different input data, such as DNase/ATAC-seq or histone data.
It will create a folder called 'rgt_test' in the home directory, and if everything works fine, you will find a footprints.bed file in HINT_HistoneTest


Best,
Li

**Comment by tombartlett** [comment]
Hi,

Many thanks for your response!

I confirm that I have been able to run the test script correctly (the output is pasted below). If this test script ran OK, I guess maybe there is some problem with the files I was trying to process with HINT? Just wondering if you have any suggestions how to check this?

Thanks again for your help with this,

Tom




Running HINT using ATAC-seq data..


[total time: 0h 1m 7s]

Testing the paired-end model of HINT using ATAC-seq data..


[total time: 0h 1m 32s]

Running HINT using only histone modification data..

Downloading test data.

HINT_HistoneTest/

HINT_HistoneTest/histone.bam

HINT_HistoneTest/histone.bam.bai

HINT_HistoneTest/histonePeaks.bed

HINT_HistoneTest/test.bed

HINT_HistoneTest/test.info


[total time: 0h 0m 16s]

********* HINT test completed ****************




________________________________

**Comment by lzj1769** [comment]
Hi,

>  If this test script ran OK, I guess maybe there is some problem with the files I was trying to process with HINT? 

yes, I think so

> Just wondering if you have any suggestions how to check this?

maybe you can check the input peaks, usually, I only use the normal chromosomes, i.e., chr1-22, chrX and chrY for human,
the error message is saying rgt-hint cannot find a chromosome, which is named '1'

Best,
Li

**Comment by tombartlett** [comment]
Hi,

Thanks again for all your help with this.

The input peaks I'm using are just the standard narrowPeaks output from macs2, and seemed to just be called 1, 2, ... X (etc) there. In outline (starting with the H3K4me3 ChIP-seq fastq files), I did alignment with bowtie2, then sorted and indexed etc with samtools, and finally did peak-calling with macs2.

As a test, I tried changing the chromosome names from "1" to "chr1" and "X" to "chrX" etc (I'm not using chromosomes outside the usual set!) but it still didn't fix this. I now get the error:


Traceback (most recent call last):

  File "/home/ucbptba/.python3local/bin/rgt-hint", line 8, in <module>

    sys.exit(main())

  File "/home/ucbptba/.python3local/lib/python3.8/site-packages/rgt/HINT/Main.py", line 95, in main

    args.func(args)

  File "/home/ucbptba/.python3local/lib/python3.8/site-packages/rgt/HINT/Footprinting.py", line 114, in footprinting_run

    histone(args)

  File "/home/ucbptba/.python3local/lib/python3.8/site-packages/rgt/HINT/Footprinting.py", line 599, in histone

    histone_norm, histone_slope = reads_file.get_signal(ref=r.chrom, start=r.initial, end=r.final,

  File "/home/ucbptba/.python3local/lib/python3.8/site-packages/rgt/HINT/signalProcessing.py", line 120, in get_signal

    iter = self.bam.fetch(reference=ref, start=start, end=end)

  File "pysam/libcalignmentfile.pyx", line 1081, in pysam.libcalignmentfile.AlignmentFile.fetch

  File "pysam/libchtslib.pyx", line 687, in pysam.libchtslib.HTSFile.parse_region

ValueError: invalid contig `chr1`


Any other suggestions of what to check here would be much appreciated!

Best wishes,

Tom

________________________________

**Comment by lzj1769** [comment]
Hi @tombartlett ,

Update, 
One of our colleagues also had this problem, and it turns out in the BAM file, for each read, there is no chr as the prefix of genomic coordinate. 

you can check it up by:
`samtools view your_bam_file | head`

To solve it, probably try to add chr to the bam file with following tutorial:
https://josephcckuo.wordpress.com/2016/11/17/modify-chromosome-notation-in-bam-file/

best,
Li
