### ISSUE TITLE
THOR needs to get rid of HTSeq dependency

### ISSUE THREAD

**Issue by fabioticconi** [CostaLab/reg-gen#19]
That dependency is a relic from ODIN, but it is used by the normalisation factor function so we should refactor that.

**Comment by fabioticconi** [comment]
The file normalize.py is the one to look at, @KFDing

**Comment by fabioticconi** [comment]
@KFDing, we can hold off on this for. After speaking with Ivan, it's not worth the effort to remove it - and it may actually be more efficient than alternatives.

**Comment by KFDing** [comment]
http://blog.minitab.com/blog/adventures-in-statistics-2/how-to-correctly-interpret-p-values
