### ISSUE TITLE
The column description of bed files from rgt-TDF regiontest

### ISSUE THREAD

**Issue by yewero** [CostaLab/reg-gen#192]
For example, I ran the command in the tutorial:
`rgt-TDF regiontest -r MEG3_sequence.fa -bed MEG3_hg38_CHOP.bed -rn MEG3 -organism hg38 -o MEG3 -n 100 -l 14`
After that I got two `bed` files:

> MEG3_target_region_dbs.bed
> MEG3_dbss.bed

Where could I find the description for each column in the `bed` files?

**Comment by chaochungkuo** [comment]
Hi, was your question about the general description for BED format? If yes, you can find more details here:
https://genome.ucsc.edu/FAQ/FAQformat.html

Please let me know if you are asking something else.

**Comment by yewero** [comment]
@chaochungkuo Thanks. I know the classic `bed` format. Instead, I need to know the meaning of columns in the `bed` format from `rgt-TDF regiontest`.

**Comment by chaochungkuo** [comment]
Hi @yewero 

There are two BED files in the result folder and their explanation are as below. Here I take _MEG3_ as the example.

**==> MEG3_dbss.bed <==**
```
chr1	12105433	12105448	1096-1111-A	12	-	TNFRSF8
chr1	12105437	12105453	1499-1515-A	13	-	TNFRSF8
chr1	12105525	12105540	24-39-A	12	-	TNFRSF8
chr1	12113520	12113535	1458-1473-P	12	+	TNFRSF8
chr1	12113522	12113537	967-982-P	12	+	TNFRSF8
chr1	12113610	12113625	1458-1473-P	12	+	TNFRSF8
chr1	12113612	12113627	967-982-P	12	+	TNFRSF8
chr1	12113632	12113647	442-457-P	12	+	TNFRSF8
chr1	12113734	12113749	442-457-P	12	+	TNFRSF8
chr1	12113892	12113907	695-710-P	12	+	TNFRSF8
```
This file includes all individual predicted DBS (DNA Dinding sites) on DNA. They may overlap with one another. This is the same as genomic_region_test/MEG3/region_dbs.html
![Screenshot from 2021-08-23 22-14-22](https://user-images.githubusercontent.com/6841506/130513203-d865b321-1291-494b-9268-98e14514b150.png)
![Screenshot from 2021-08-23 22-17-06](https://user-images.githubusercontent.com/6841506/130513540-af776ade-cba3-42e8-85f9-7bcd6bbd9203.png)


**==> MEG3_target_regions.bed <==**
```
chr4	48659232	48659877	FRYL	64	.	99.22	0.72	2
chr7	90895138	90895671	CDK14	61	.	114.45	0.49	13
chr10	2986966	2987894	RP11-118K6.3(+)	56	.	60.34	0.43	18
chr1	164453600	164454184	HMGB3P6(-)	51	.	87.33	0.54	13
chr18	47458242	47458988	CTD-2130O13.1	51	.	68.36	0.53	15
chr22	43432068	43433126	MPPED1	51	.	48.20	0.57	11
chr6	20168288	20169236	MBOAT1	51	.	53.80	0.32	35
chr3	153318643	153319732	RP11-292E2.1(+)	48	.	44.08	0.35	33
chr18	10368348	10369028	RP11-138E9.2	45	.	66.18	0.43	25
chr18	47982262	47983012	RP11-380M21.3(-):ZBTB7C(+)	44	.	58.67	0.38	35
```
This file summarizes the information of DBSs for each given DNA region. Each row is the region from the input file with additional information. This is exactly the same as HTML report in genomic_region_test/MEG3/target_regions.html
![Screenshot from 2021-08-23 22-10-34](https://user-images.githubusercontent.com/6841506/130512801-170f5b13-9d0f-409f-ae46-482176c8e39b.png)

I should add this explanation into the tutorial. Please let me know if it isn't clear.

**Comment by yewero** [comment]
@chaochungkuo It's clear, thanks.
