### ISSUE TITLE
Question regarding multiple samples for differential footprinting analysis

### ISSUE THREAD

**Issue by LaraBM** [CostaLab/reg-gen#193]
Hi there, 

I have a cohort of ATAC-Seq samples and have found your tutorial extremely useful and have been successful in following it. I do have a question about multiple samples with the rgt-hint differential command though.

My samples can be split into 2 conditions. Can all samples be used to perform a differential TF analysis and how would the syntax for this look? The tutorial only shows the case of a 1:1 analysis. I have attempted this and I'm not sure if it does work or not...I have run 17 samples through for 60 hours on our HPC on a highmem node but nothing was produced at the end (except an empty Lineplots directory); my first attempt with a 1:1 analysis took just a little over 12 hours. I have attached some example code to show how I thought to do it... (I have also used parameters in the way described by the "help" in the software as opposed to the tutorials as I think the tutorials may be slightly outdated?...):

`rgt-hint differential --organism=hg38 --bc --nc 64 --mpbs-files=/filepath/match/file1cond1_mpbs.bed,/filepath/match/file2cond1_mpbs.bed,/filepath/match/file3cond1_mpbs.bed,/filepath/match/file4cond1_mpbs.bed,/filepath/match/file5cond1_mpbs.bed,/filepath/match/file6cond2_mpbs.bed,/filepath/match/file7cond2_mpbs.bed,/filepath/match/file8cond2_mpbs.bed,/filepath/match/file9cond2_mpbs.bed,/filepath/match/file10cond2_mpbs.bed, --reads-files=/filepath/bams/file1.bam,/filepath/bams/file2.bam,/filepath/bams/file3.bam,/filepath/bams/file4.bam,/filepath/bams/file5.bam,/filepath/bams/file6.bam,/filepath/bams/file7.bam,/filepath/bams/file8.bam,/filepath/bams/file9.bam,/filepath/bams/file10.bam --conditions=condition1,condition1,condition1,condition1,condition1,condition2,condition2,condition2,condition2,condition2, --output-location=Condition1_Condition2`

Please let me know if this command doesn't let you use multiple samples or if it does, how I should make this work.

Many thanks!
Lara

**Comment by lzj1769** [comment]
Hi @LaraBM ,

> I have a cohort of ATAC-Seq samples and have found your tutorial extremely useful and have been successful in following it. I do have a question about multiple samples with the rgt-hint differential command though.

Sorry for the late reply.

> My samples can be split into 2 conditions. Can all samples be used to perform a differential TF analysis and how would the syntax for this look? The tutorial only shows the case of a 1:1 analysis. I have attempted this and I'm not sure if it does work or not...I have run 17 samples through for 60 hours on our HPC on a highmem node but nothing was produced at the end (except an empty Lineplots directory); my first attempt with a 1:1 analysis took just a little over 12 hours. I have attached some example code to show how I thought to do it... (I have also used parameters in the way described by the "help" in the software as opposed to the tutorials as I think the tutorials may be slightly outdated?...):

Yes, you can input all samples to differential TF footprinting, and in this case, the data will be normalized together. We have provided a tutorial to show how to use HINT-ATAC to compare more than two conditions:
https://www.regulatory-genomics.org/hint/tutorial-differential-footprints-on-scatac-seq/

> Please let me know if this command doesn't let you use multiple samples or if it does, how I should make this work.

If I understand it correctly, you have two conditions and each of them has multiple samples, right? Are these samples are just replicates? If this is the case, I would recommend to first merge them to create a BAM for each condition,  and then run 1 vs 1 differential TF analysis.

Let me know if you have any questions. :)

best,
Li

**Comment by LaraBM** [comment]
Hi @lzj1769 ,

My apologies for the late response! I have been away so only getting back to work now!

> We have provided a tutorial to show how to use HINT-ATAC to compare more than two conditions:
https://www.regulatory-genomics.org/hint/tutorial-differential-footprints-on-scatac-seq/

Thank you for the link to the tutorial. This too presents the case where you have one sample per condition, as opposed to multiple samples per condition, and so you still complete a 1:1:1 analysis. 

> If I understand it correctly, you have two conditions and each of them has multiple samples, right? Are these samples are just replicates? If this is the case, I would recommend to first merge them to create a BAM for each condition, and then run 1 vs 1 differential TF analysis.

They are biological replicates so I have merged them by condition as you suggested (not sure if you meant we can merge if they are technical replicates only?). Is there a way to do this without merging by any chance? There are a few conditions I can categorise these samples under and merging them in different combinations doesn't seem to be the best idea...but I appreciate that if there are too many samples, the time to process and analyse the samples may become an issue.

Many thanks for your help! :)

Kind regards,
Lara

**Comment by lzj1769** [comment]
Hi Lara,

>  Is there a way to do this without merging by any chance? There are a few conditions I can categorise these samples under and merging them in different combinations doesn't seem to be the best idea...

You can run the analysis without merging them, and after it's done, you will have the results for each sample.
Depending on what conclusion you want to draw, the results can be further analyzed.

> but I appreciate that if there are too many samples, the time to process and analyse the samples may become an issue.

You can specify the multi-core options which will use multiple cups for computation and will reduce the time significantly. 

Best,
Li

**Comment by lzj1769** [comment]
closed if no further comments.
