### ISSUE TITLE
add mm39 genome

### ISSUE THREAD

**Issue by fabio-t** [CostaLab/reg-gen#194]

**Comment by fabio-t** [comment]
should be fine, merged to developed but I haven't tried running something on it.

@lzj1769 This was requested for HINT-ATAC, so maybe you could try running the program on mm39 to see it produces similar results to mm10? It's pushed to develop now.

Here's the changeset if you want to have a look: https://github.com/CostaLab/reg-gen/commit/e9d7ca9705bd172e94a349dd31b307d5d1fc4719

**Comment by lzj1769** [comment]
`@lzj1769 This was requested for HINT-ATAC, so maybe you could try running the program on mm39 to see it produces similar results to mm10? It's pushed to develop now.`

Thanks @fabio-t, I will check it out.

**Comment by lzj1769** [comment]
mm39 is added to the latest version and this issue is closed now.

**Comment by palmiralg** [comment]
Hello. I've just installed RGT to perform HINT-ATAC on mouse ATAC-seq data that has been aligned to mm39. @lzj1769 said

> "mm39 is added to the latest version and this issue is closed now."

 but when I look at the rgtdata folder, the mm39 assembly isn't there. 

```
python setupGenomicData.py --mm39
usage: setupGenomicData.py [-h] [--all] [--hg19] [--hg38] [--mm9] [--mm10] [--zv9] [--zv10] [--hg19-genome-path STRING] [--hg38-genome-path STRING]
                           [--mm9-genome-path STRING] [--mm10-genome-path STRING] [--zv9-genome-path STRING] [--zv10-genome-path STRING] [--hg19-gtf-path STRING]
                           [--hg38-gtf-path STRING] [--mm9-gtf-path STRING] [--mm10-gtf-path STRING] [--zv9-gtf-path STRING] [--zv10-gtf-path STRING] [--hg38-rm]
                           [--hg19-rm] [--mm9-rm]
setupGenomicData.py: error: unrecognized arguments: --mm39
```

Could you please help me? Thank you
