### ISSUE TITLE
Failed to open FASTA index 

### ISSUE THREAD

**Issue by maojn** [CostaLab/reg-gen#195]
Hi,
I ran setupGenomicData.py --all to install the data. But when I ran the tutorial I got the error saying:
[E::fai_build3_core] Failed to open FASTA index /xxx/mm10/genome_mm10.fa.fai : Permission denied

Do I need to manually index genome_mm10.fa with samtools faidx genome_mm10.fa? Which version of samtools should I use? Thanks!

**Comment by lzj1769** [comment]
Hi,

`Which version of samtools should I use?`
Basically, any version samtools should be working.
Let me know if the problem still exists. 

best,
Li

**Comment by lzj1769** [comment]
Closed as no further comments, feel free to re-open it if there are any questions.
