### ISSUE TITLE
THOR fails: numpy float to integer

### ISSUE THREAD

**Issue by mpi-pebert** [CostaLab/reg-gen#20]
Hi,
I am running THOR in an environment with `Python 2.7.13` and `numpy 1.12.1`. THOR version 0.1 as downloaded from the website. The run fails due to the following:
```python
  File "[...]/conda/envs/thor/lib/python2.7/site-packages/RGT-0.0.1-py2.7.egg/rgt/THOR/dpc_help.py", line 198, in _fit_mean_var_distr
    _plot_func(plot_data, outputdir)
  File "[...]/conda/envs/thor/lib/python2.7/site-packages/RGT-0.0.1-py2.7.egg/rgt/THOR/dpc_help.py", line 107, in _plot_func
    x = linspace(0, max(plot_data[i][0]), max(plot_data[i][0])+1)
  File "[...]/conda/envs/thor/lib/python2.7/site-packages/numpy/core/function_base.py", line 101, in linspace
    num = _index_deprecate(num)
  File "[...]/conda/envs/thor/lib/python2.7/site-packages/numpy/core/function_base.py", line 21, in _index_deprecate
    warnings.warn(msg, DeprecationWarning, stacklevel=stacklevel)
DeprecationWarning: object of type <type 'numpy.float64'> cannot be safely interpreted as an integer.
```
Best,
Peter

**Comment by fabioticconi** [comment]
Hi Peter,

thanks for your report. Looks like in numpy 1.12 they finally removed something that was deprecated for a while.

As a quick fix, you may try to install **numpy 1.11.0**. It should work. We're going to look at this soon.

As a side note, unless you specifically need THOR 0.1, be aware that we are now releasing via pip:

```
pip install --user RGT
```

If you prefer to install manually, the latest releases are here: https://github.com/CostaLab/reg-gen/releases

**Comment by mpi-pebert** [comment]
I see, installed using pip and `numpy 1.11.0` this time - so far running fine, just an ugly warning when starting it:
```bash
[...]/conda/envs/thor/lib/python2.7/site-packages/matplotlib/__init__.py:1401: UserWarning:
This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

 warnings.warn(_use_error_msg)
```
I'll let you know if anything serious pops up.
Thanks.

+Peter

**Comment by jovesus** [comment]
This ugly warning is fixed and will be included in the next release.

Thank you.

*Joseph Chao-Chung Kuo*

**Comment by fabioticconi** [comment]
@mpi-pebert we can confirm that in the newest THOR that you now have, even using numpy 1.12 is fine. We had fixed that already.

**Comment by mpi-pebert** [comment]
Alright, thanks for the info
