### ISSUE TITLE
Example results run by my hand is not consistent with the tutorial

### ISSUE THREAD

**Issue by hyjforesight** [CostaLab/reg-gen#200]
Hello RGT,
I'm running this RGT-HINT tutorial (http://www.regulatory-genomics.org/hint/tutorial/). For the `rgt-hint differential` step, the scatter plot I got is not consistent with the tutorial.
```linux
rgt-hint differential --organism mm9 --mpbs-files /home/hyjforesight/DendriticCells/match/footprint_cDC1_mpbs.bed,/home/hyjforesight/DendriticCells/match/footprint_pDC_mpbs.bed --reads-files /home/hyjforesight/DendriticCells/cDC1.bam,/home/hyjforesight/DendriticCells/pDC.bam --conditions cDC1,pDC --window-size 200 --fdr 0.05 --bc --nc 40 --output-location /home/hyjforesight/DendriticCells/ --output-prefix differential
```
Here is the scatter plot I got.
![image](https://user-images.githubusercontent.com/75048821/161087563-a8aed7d5-5c18-4736-9c10-20e976d4abc4.png)
Here is the scatter plot that the tutorial shows.
![image](https://user-images.githubusercontent.com/75048821/161087692-1feecc87-ba6f-4e9d-bca7-5071eb9ccef7.png)

Is it because some random seed was used internally, so that every run will generate different results?
Thanks!
Best,
YJ

**Comment by lzj1769** [comment]
Closing this issue if no new comments.
