### ISSUE TITLE
Hint footprint stuck at "Matplotlib is building the font cache; this may take a moment" for a day

### ISSUE THREAD

**Issue by BW15061999** [CostaLab/reg-gen#206]
Hi,
is it normal while running footprinting?

Thanks!

**Comment by lzj1769** [comment]
Hi,

This absolutely is not normal.
It means that the matplotlib cannot be imported properly.

See here for example:
https://stackoverflow.com/questions/34771191/matplotlib-taking-time-when-being-imported

**Comment by BW15061999** [comment]
HI,

It didn't show this message this time, thanks!
And I also wonder how long does it take to run footprinting using 8 cores?

Best

**Comment by lzj1769** [comment]
Hi, 

The running time depends on the number of input samples.
With two samples, it usually completes in 1 hour.

**Comment by lzj1769** [comment]
Closed if no further questions. Feel free to re-open it.
