### ISSUE TITLE
quantification of footprint

### ISSUE THREAD

**Issue by qingnanl** [CostaLab/reg-gen#207]
Dear authors,

Thanks for building these tools. I would like to ask about the footprint analysis: is there a quantification metric for the footprint inferred by hint-atac? With the default, the output is a bed file with the location of the footprint. I understand that the 'column 5' somehow indicates the size of the peak (the larger, the higher reliability of the data). Just want to know if there are other metrics (even if a p-value) indicating how likely the footprint is real. I did see some hidden options in the hint-atac python code, but I do not fully understand the meaning of the options. Thanks.

qingnanl

**Comment by lzj1769** [comment]
Hi @qingnanl 

The 5th column represents the number of reads around the predicted footprint. 
Based on our evaluation, this value is a good metric for selecting good footprints.

So, you can use a threshold to pick up a number of footprints.

best,
Zhijian

**Comment by qingnanl** [comment]
Thanks, Zhijian. That is very helpful. Let me close this.
Best,

qingnanl
