### ISSUE TITLE
Cannot install THOR

### ISSUE THREAD

**Issue by JohnsonStev** [CostaLab/reg-gen#217]
Hi

After following the instructions on the webpage to install the rgt tools, I ran into this error while try to execute THOR
![image](https://user-images.githubusercontent.com/38938938/180060041-3b49b081-238f-4736-9521-15b9f274b840.png)

This seems to be a problem with numpy (I am using 1.23.1)
btw, most other rgt programs seemed to work fine. 

Thank you for your help

**Comment by lzj1769** [comment]
Hi,

I think this may be caused by different versions of NumPy.
Can you re-install numpy and see if it works?

```
pip uninstall numpy
pip install numpy
```

**Comment by lzj1769** [comment]
Closed if no further comments.
