### ISSUE TITLE
add bos taurus genome 

### ISSUE THREAD

**Issue by ZgtL15** [CostaLab/reg-gen#218]
Hi,
I tried to use rgt today ,but did not find any data of bos taurus genome. And i try to add bos taurus genome. I add this info to  data.config.user 
![image](https://user-images.githubusercontent.com/74951994/183323328-14467575-f5b1-4cf8-944c-187a9f526951.png)
And i don't know how to continue ,i tried the commend "python setupGenomicData.py --bt8",and it didn't work.
Looking forward to your reply,Thanks a lot !

**Comment by ZgtL15** [comment]
Hi,i find the way to load bos taurus genome,but a new problem arised 
![image](https://user-images.githubusercontent.com/74951994/183333459-3aec5748-0439-4164-957a-f8db35c2c1cf.png)
i tried to change my 'data.config.users' "gene_regions "to "genes_gencode"or"genes_Gencode",but it still had the same error .my rgt version is 0.12.3. and i can't update or install the newest version

**Comment by lzj1769** [comment]
Hi,

Would be possible for you to share with me the data for bos taurus genome?

Or maybe you can tell me where to find them, so I can add this to our setupGenomicData.py

Thanks,
Li

**Comment by lzj1769** [comment]
Hi @ZgtL15 ,

I have added the bt8 genome in the setupGenomicData.py and now you can just run the script in install bt8 genome.

First install rgt from develop branch

```
git clone git@github.com:CostaLab/reg-gen.git
cd reg-gen
git checkout develop
pip install ./
```
Then, go to ~/rgtdata directory and download the data:
```
cd ~/rgtdata
python setupGenomicData.py --bt8
```

Let me know if this works for you.

Best,
Zhijian

**Comment by ZgtL15** [comment]
Hi,
Thanks for your reply!
I have configured the newest setupGenomicData.py
![image](https://user-images.githubusercontent.com/74951994/185015326-b7d9f567-d33d-406d-ba0c-e37625222e2a.png)
but my download is so low,so it need quite a while,so is there any methods i can add it used local file,cause besides bostau8 genome ,i also need the bostau9(UCD1.2/1.3) genome (from ensembl).
Thanks a lot !
Best,
ZgtL15

**Comment by lzj1769** [comment]
Hi,

>  is there any methods i can add it used local file,cause besides bostau8 genome ,i also need the bostau9(UCD1.2/1.3) genome (from ensembl).

Yes, we here provided a tutorial about how to customize the data:
https://reg-gen.readthedocs.io/en/latest/rgt/setup_data.html

Can you try to follow it can see if everything is fine?

Best,
Zhijian

**Comment by ZgtL15** [comment]
Hello, 
Thanks for  your reply!
I have added the bos taurus genome successfully ! Thanks for helping!

**Comment by lzj1769** [comment]
Glad it's working now. I will close this issue and feel free to re-open it if there are other questions.
