### ISSUE TITLE
RGT-HINT Wrong Species TF Hits

### ISSUE THREAD

**Issue by gulumy** [CostaLab/reg-gen#230]
Hello,

I have successfully ran RGT Hint to do differential transcription factor foot printing for ATACseq data. I am using RGT's HG38 human genome to align my data to, and have specified that the species is human in many steps. However, some of the differentially activated transcription factor hits I am getting include TFs from Mus musculus (such as MA0601.1.Arid3b)
and Xenopus laevis (such as MA0621.1.mix-a), although most of them are human. These transcription factors also have a significant number of reads and they come up no matter how I analyze the data. Has anyone else had this issue before? What does it mean and how can I fix it?

**Comment by lzj1769** [comment]
Thanks @Andi964 for your input.
