### ISSUE TITLE
rgt shifting

### ISSUE THREAD

**Issue by Andi964** [CostaLab/reg-gen#233]
Hello,
i have two questions regarding the rgt-hint footprinting function:

A) Does this command using the 
`--atac-seq`
argument include proper Tn5-shifting, or do we have to shift the data before?
B) Can/should the
` --bias-correction` 
argument be applied for atac-seq data?

Best,
Andreas

**Comment by lzj1769** [comment]
Hi,

Yes, the —atac-seq argument will automatically enable Tn5 shifting, so you don’t need to do it before.

By default, —atac-seq will also include the bias correction.


Best,
Li

----------------------------------------------------------
Zhijian Li
Institute for Computational Genomics
RWTH Aachen University
Pauwelsstrasse 19
Aachen, Germany
