### ISSUE TITLE
RGT-HINT:How to input more than one replicate during one group 

### ISSUE THREAD

**Issue by wvdon** [CostaLab/reg-gen#238]
I have two group. each group including more than one bam and peak.,so ,how deal with the Footprinting in  `rgt-hint differential ` or rgt-motifanalysis matching. Could I deal with 'samtoos merge' simply these bam ?
Thanks! Hope for u r answer!

Best Wishes!

**Comment by lzj1769** [comment]
Hi @wvdon 

Exactly, you can just merge the bam files for each group. To get peaks, you can either do the peak calling again based on the merged bam file, or simply combine the bed files.

Best,
Zhijian
