### ISSUE TITLE
KeyError: 'GL456233.2'

### ISSUE THREAD

**Issue by czfoo** [CostaLab/reg-gen#243]
I got this error message when trying to run HINT-ATAC using peak files previously generated by Genrich using the mm39 genome. What does this error mean and how can I rectify it?

**Comment by lzj1769** [comment]
Hi @czfoo 

This means that rgt-hint cannot find the DNA sequences for this chromosome. 
What I usually do is only keep peaks from norm chromosomes, for example, for mouse using chr1-19 and chrX,
for human, only using chr1-23 and chrX.

**Comment by czfoo** [comment]
Thanks so much. It works now.
