### ISSUE TITLE
rgt-hint throwing an error (without any other input) post-installation (Linux)

### ISSUE THREAD

**Issue by sufyazi** [CostaLab/reg-gen#247]
Hi, 

I installed RGT on a remote Linux machine and strangely, even when the installation completed successfully, only `rgt-hint` throws out an error when I simply run `rgt-hint` or 'rgt-hint footprinting --help'. 

The exact error is as below:

```
raceback (most recent call last):
  File "/home/suffi.azizan/.local/bin/rgt-hint", line 33, in <module>
    sys.exit(load_entry_point('RGT==1.0.0', 'console_scripts', 'rgt-hint')())
  File "/home/suffi.azizan/.local/bin/rgt-hint", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/suffi.azizan/.local/lib/python3.6/site-packages/rgt/HINT/Main.py", line 16, in <module>
    from rgt.HINT.DifferentialAnalysis import diff_analysis_args, diff_analysis_run
  File "/home/suffi.azizan/.local/lib/python3.6/site-packages/rgt/HINT/DifferentialAnalysis.py", line 26, in <module>
    from adjustText import adjust_text
  File "/home/suffi.azizan/.local/lib/python3.6/site-packages/adjustText/__init__.py", line 1
    from __future__ import division, annotations
    ^
SyntaxError: future feature annotations is not defined
```
It is like the error is in the code itself, but I don't understand why this is the case when I was not able to find anyone else complaining of the same error for the v1.0. 

When I run other subcommands, such as `rgt-THOR --help`, expectedly I see this:

```
Usage:
rgt-THOR [options] CONFIG

THOR detects differential peaks in multiple ChIP-seq profiles associated
with two distinct biological conditions.

Copyright (C) 2014-2016  Manuel Allhoff (allhoff@aices.rwth-aachen.de)

This program comes with ABSOLUTELY NO WARRANTY. This is free
software, and you are welcome to redistribute it under certain
conditions. Please see LICENSE file for details.


Options:
  -h, --help            show this help message and exit
  -n NAME, --name=NAME  Experiment's name and prefix for all files that are
                        created.
  -m, --merge           Merge peaks which have a distance less than the
                        estimated mean fragment size (recommended for histone
                        data). [default: do not merge]
  --no-merge-bin        Merge the overlapping bin before filtering by
                        p-value.[default: Merging bins]
  --housekeeping-genes=HOUSEKEEPING_GENES
                        Define housekeeping genes (BED format) used for
                        normalizing. [default: none]
```
(truncated)

I have tested other RGT subcommands and they all showed the help page when run without any arguments/not enough arguments. 

I installed via `pip` and I have made sure it is updated as recommended in your installation page. I am using Python 3. Can someone help diagnose what is the issue here?

**Comment by lzj1769** [comment]
Hi, 

From the message, the issue was caused by the **adjustText** package.

Can you check the version of this package?

Best,
Zhijian

**Comment by sufyazi** [comment]
Hi my *adjustText* package is of the version 0.8. Which is the latest one. Anything else I should check?

**Comment by sufyazi** [comment]
I found a clue here: https://stackoverflow.com/questions/70515194/syntaxerror-future-feature-annotations-is-not-defined

From the error message above, it seems like my version of RGT on the remote machine is installed under 'python3.6' which does not support the syntax `from __future__ import...`. So maybe this is the issue? When I ran `pip uninstall RGT` it clearly showed below that RGT was installed in Python 3.6 `site_packages`. 

```
Found existing installation: RGT 1.0.0
Uninstalling RGT-1.0.0:
  Would remove:
    /home/suffi.azizan/.local/bin/bedGraphToBigWig
    /home/suffi.azizan/.local/bin/bedToBigBed
    /home/suffi.azizan/.local/bin/bigBedToBed
    /home/suffi.azizan/.local/bin/bigWigMerge
    /home/suffi.azizan/.local/bin/rgt-TDF
    /home/suffi.azizan/.local/bin/rgt-THOR
    /home/suffi.azizan/.local/bin/rgt-hint
    /home/suffi.azizan/.local/bin/rgt-motifanalysis
    /home/suffi.azizan/.local/bin/rgt-viz
    /home/suffi.azizan/.local/bin/wigToBigWig
    /home/suffi.azizan/.local/lib/python3.6/site-packages/RGT-1.0.0-py3.6.egg-info
    /home/suffi.azizan/.local/lib/python3.6/site-packages/rgt/*
Proceed (Y/n)? y
  Successfully uninstalled RGT-1.0.0
```

I am actually trying to make RGT work on an HPC cluster (we are allowed to install programs in our user space). The problem now is I do not know how to direct the installation so that RGT is installed under Python >3.6. I have several python environments on Conda on my user space but it seems like even when I created a specific environment for RGT installation, pip install it under Python 3.6. Not sure what I do wrong and how to fix this.

**Comment by lzj1769** [comment]
Hi,

I now understand your point.


Here is how I usually run rgt on a HPC cluster by creating a specific conda environment named as rgt:

```
conda create -n rgt python
conda activate rgt
pip install --user cython numpy scipy
pip install rgt
```

Then you can try to check if it works by:

`rgt-hint --help`

**Comment by sufyazi** [comment]
Hi,

Based on this (https://stackoverflow.com/questions/42988977/what-is-the-purpose-of-pip-install-user), I figured out what I did wrong before I saw your reply. the `--user` actually installed RGT under my user space but on my `base` conda environment. I started again on a fresh slate by creating a new environment and explicitly asking for fresh install of python and pip. I then installed `rgt` and the other packages as you described above.

The install looks right but another strange error, specifically just for `rgt-hint` comes up. I have made sure `numpy` and `scipy` are the latest in terms of version. What could be going wrong here? 

Here's the full error log:

```
Traceback (most recent call last):
  File "/home/suffi.azizan/installs/mambaforge-pypy3/envs/rgt-suite/bin/rgt-hint", line 5, in <module>
    from rgt.HINT.Main import main
  File "/home/suffi.azizan/installs/mambaforge-pypy3/envs/rgt-suite/lib/python3.11/site-packages/rgt/HINT/Main.py", line 14, in <module>
    from rgt.HINT.Training import training_args, training_run
  File "/home/suffi.azizan/installs/mambaforge-pypy3/envs/rgt-suite/lib/python3.11/site-packages/rgt/HINT/Training.py", line 10, in <module>
    from rgt.HINT.signalProcessing import GenomicSignal
  File "/home/suffi.azizan/installs/mambaforge-pypy3/envs/rgt-suite/lib/python3.11/site-packages/rgt/HINT/signalProcessing.py", line 6, in <module>
    from numpy import exp, array, abs, int, mat, linalg, convolve, nan_to_num
ImportError: cannot import name 'int' from 'numpy' (/home/suffi.azizan/installs/mambaforge-pypy3/envs/rgt-suite/lib/python3.11/site-packages/numpy/__init__.py)
```
Would appreciate your help.

**Comment by lzj1769** [comment]
Hi,

Thanks for reporting this, and I will fix the README to remove --user option.

Regarding the problem from numpy, I have fixed it in the develop branch, so you can install it from source code by:

```
git clone git@github.com:CostaLab/reg-gen.git
cd reg-gen
git checkout develop
pip install ./
```

**Comment by sufyazi** [comment]
Sorry I am not able to `git clone` it. What am I doing wrong? 

```
❯ git clone git@github.com:CostaLab/reg-gen.git
Cloning into 'reg-gen'...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s.
Please contact your system administrator.
Add correct host key in /Users/sufyazi/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/sufyazi/.ssh/known_hosts:8
Host key for github.com has changed and you have requested strict checking.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by lzj1769** [comment]
Hi,

I think this is related to the cluster permission.

To download the source code, you can also try
`git clone https://github.com/CostaLab/reg-gen.git`

**Comment by sufyazi** [comment]
Thank you! The hotfix works on my end after reinstalling the develop branch version. Closing this now.
