### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by li1311139481** [CostaLab/reg-gen#249]
I'm doing differential footprinting analysis with the rgt-hint.
When i use
`  rgt-hint differential --organism=mm10 --bc --nc 30 \
--mpbs-files=match/WT_mpbs.bed,match/KO_mpbs.bed \
--reads-files=diffbind/2023_04_17_consensus_peaks_WT.bam,diffbind/2023_04_17_consensus_peaks_KO.bam \
--conditions=WT,KO \
--output-location=KO_WT `
I get an error like
`144 cpus are detected and 30 of them will be used...

generating signal for each motif and condition...

generating signal for condition WT

generating signal for condition KO

signal generation is done!

generating line plot for each motif...

posx and posy should be finite values
posx and posy should be finite values

Traceback (most recent call last):
  File "/cluster/facility/hlhuang/miniconda3/envs/pip/bin/rgt-hint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/cluster/facility/hlhuang/miniconda3/envs/pip/lib/python3.11/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/cluster/facility/hlhuang/miniconda3/envs/pip/lib/python3.11/site-packages/rgt/HINT/DifferentialAnalysis.py", line 267, in diff_analysis_run
    volcano_plot(args, ps_tc_results, mpbs_name_list, conditions)
  File "/cluster/facility/hlhuang/miniconda3/envs/pip/lib/python3.11/site-packages/rgt/HINT/DifferentialAnalysis.py", line 687, in volcano_plot
    plt.xlim(-ceil(np.max(np.abs(df['log2FoldChange']))), ceil(np.max(np.abs(df['log2FoldChange']))))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: cannot convert float infinity to integer`

This is my environment: 
bzip2                     1.0.8                h7f98852_4    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2022.12.7            ha878542_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
contourpy                 1.0.7                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.34                  pypi_0    pypi
fisher                    0.1.10                   pypi_0    pypi
fonttools                 4.39.3                   pypi_0    pypi
hmmlearn                  0.2.2                    pypi_0    pypi
htseq                     2.0.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.40                 h41732ed_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libexpat                  2.5.0                hcb278e6_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h7f98852_5    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 12.2.0              h65d4601_19    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libgomp                   12.2.0              h65d4601_19    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libnsl                    2.0.0                h7f98852_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libsqlite                 3.40.0               h753d276_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libuuid                   2.38.1               h0b41bf4_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.2.13               h166bdaf_4    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
logomaker                 0.8                      pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-venn           0.11.9                   pypi_0    pypi
moods-python              1.9.4.1                  pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
natsort                   8.3.1                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
numpy                     1.24.2                   pypi_0    pypi
openssl                   3.1.0                h0b41bf4_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.0                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.1               pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
pybigwig                  0.3.22                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pysam                     0.21.0                   pypi_0    pypi
python                    3.11.3          h2755cc3_0_cpython    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyx                       0.16                     pypi_0    pypi
readline                  8.2                  h8228510_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
rgt                       1.0.1                    pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
seaborn                   0.12.2                   pypi_0    pypi
setuptools                67.7.1             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
six                       1.16.0                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
tzdata                    2023.3                   pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
xz                        5.2.6                h166bdaf_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge

I couldn't find any answers in the communities in question. How to solve this problem

**Comment by lzj1769** [comment]
Hi,

This seems to be related to the scatter plot, 
@minashaigan Can you help with this issue?

Best,
Zhijian

**Comment by li1311139481** [comment]
> 

Hi 
Thank you for your reply. 
I have found out the reason why it happened. This error occurs if the fifth column of the bed file I entered is not an integer. If the input is an integer, I will be fine. The fifth column of the bed file usually refers to the scor. The problem is that usually the narrowPeak files we get using MACS2 call peaks are not used directly for footprinting analysis with the rgt-hint, but rather merge narrowPeak files to get consensus peak files. In the process, the fifth column becomes a decimal after a series of operations.
Maybe you could tell me some good ways to find consensus peak that both make biological sense and can be directly applied to the rgt-hint, which has been bothering me for a long time.
Thank you so much

**Comment by lzj1769** [comment]
Hi,

Good to see the issue was solved.

> Maybe you could tell me some good ways to find consensus peak that both make biological sense and can be directly applied to the rgt-hint, which has been bothering me for a long time.

Since this is very specific, I think you probably need to implement a script for this task.

Best,
Zhijian
