### ISSUE TITLE
Use a standard config file format

### ISSUE THREAD

**Issue by johnmous** [CostaLab/reg-gen#25]
rgt-THOR failed with a non informative error message when an empty line was left at the bottom of the config file.
To avoid similar issues, it might be a good idea to use a standardized config format, such as yaml, in the place of a plain text file it is now in use

Error message was: 
`... 
 File ~/.local/lib/python2.7/site-packages/rgt/Util.py", line 20, in npath
    return os.path.abspath(os.path.expanduser(filename))
    if not path.startswith('~'):
AttributeError: 'list' object has no attribute 'startswith'
`

**Comment by fabioticconi** [comment]
Thanks for the report :)

**Comment by fabioticconi** [comment]
@johnmous FYI the "empty line" fix is available in the latest release, [RGT-0.10.0](https://github.com/CostaLab/reg-gen/releases/tag/0.10.0).

**Comment by johnmous** [comment]
Thanks!

**Comment by lzj1769** [comment]
Closed with no further comments.
