### ISSUE TITLE
RGT installation successful, but rgtdata folder is missing. 

### ISSUE THREAD

**Issue by mdu4003** [CostaLab/reg-gen#251]
Hello, 
I am trying to install rgt on a mac (ventura). I did: 
$ brew install python boost llvm
Warning: python@3.11 3.11.3 is already installed and up-to-date.
To reinstall 3.11.3, run:
  brew reinstall python@3.11
Warning: boost 1.81.0_1 is already installed and up-to-date.
To reinstall 1.81.0_1, run:
  brew reinstall boost
Warning: llvm 16.0.5 is already installed and up-to-date.
To reinstall 16.0.5, run:
  brew reinstall llvm
$ pip install cython numpy scipy
Requirement already satisfied: cython in ./.local/lib/python3.8/site-packages (0.29.35)
Requirement already satisfied: numpy in ./.local/lib/python3.8/site-packages (1.24.3)
Requirement already satisfied: scipy in ./.local/lib/python3.8/site-packages (1.10.1)
 $pip install RGT --no-binary RGT
Requirement already satisfied: cython in ./.local/lib/python3.8/site-packages (0.29.35)
Requirement already satisfied: numpy in ./.local/lib/python3.8/site-packages (1.24.3)
Requirement already satisfied: scipy in ./.local/lib/python3.8/site-packages (1.10.1)
MAC205928:~ diazmeco$ pip install RGT --no-binary RGT
Collecting RGT
  Using cached RGT-1.0.0-py3-none-any.whl
Requirement already satisfied: cython in ./.local/lib/python3.8/site-packages (from RGT) (0.29.35)
Requirement already satisfied: numpy>=1.4.0 in ./.local/lib/python3.8/site-packages (from RGT) (1.24.3)
Requirement already satisfied: scipy>=1.0.0 in ./.local/lib/python3.8/site-packages (from RGT) (1.10.1)
Requirement already satisfied: pysam>=0.12.0 in ./.local/lib/python3.8/site-packages (from RGT) (0.21.0)
Requirement already satisfied: pyBigWig in ./.local/lib/python3.8/site-packages (from RGT) (0.3.22)
Requirement already satisfied: Biopython>=1.64 in ./.local/lib/python3.8/site-packages (from RGT) (1.81)
Requirement already satisfied: fisher>=0.1.5 in ./.local/lib/python3.8/site-packages (from RGT) (0.1.10)
Requirement already satisfied: moods-python>=1.9.4.1 in ./.local/lib/python3.8/site-packages (from RGT) (1.9.4.1)
Requirement already satisfied: scikit-learn>=0.19.0 in ./.local/lib/python3.8/site-packages (from RGT) (1.2.2)
Requirement already satisfied: hmmlearn==0.2.2 in ./.local/lib/python3.8/site-packages (from RGT) (0.2.2)
Requirement already satisfied: pandas in ./.local/lib/python3.8/site-packages (from RGT) (2.0.2)
Requirement already satisfied: logomaker in ./.local/lib/python3.8/site-packages (from RGT) (0.8)
Requirement already satisfied: pyx in ./.local/lib/python3.8/site-packages (from RGT) (0.16)
Requirement already satisfied: joblib in ./.local/lib/python3.8/site-packages (from RGT) (1.2.0)
Requirement already satisfied: seaborn in ./.local/lib/python3.8/site-packages (from RGT) (0.12.2)
Requirement already satisfied: adjustText in ./.local/lib/python3.8/site-packages (from RGT) (0.8)
Requirement already satisfied: matplotlib>=1.1.0 in ./.local/lib/python3.8/site-packages (from RGT) (3.7.1)
Requirement already satisfied: mpmath in ./.local/lib/python3.8/site-packages (from RGT) (1.3.0)
Requirement already satisfied: HTSeq in ./.local/lib/python3.8/site-packages (from RGT) (2.0.3)
Requirement already satisfied: matplotlib-venn in ./.local/lib/python3.8/site-packages (from RGT) (0.11.9)
Requirement already satisfied: natsort in ./.local/lib/python3.8/site-packages (from RGT) (8.3.1)
Requirement already satisfied: contourpy>=1.0.1 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (1.0.7)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (4.39.4)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (1.4.4)
Requirement already satisfied: packaging>=20.0 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (23.1)
Requirement already satisfied: pillow>=6.2.0 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (5.12.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.local/lib/python3.8/site-packages (from scikit-learn>=0.19.0->RGT) (3.1.0)
Requirement already satisfied: pytz>=2020.1 in ./.local/lib/python3.8/site-packages (from pandas->RGT) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in ./.local/lib/python3.8/site-packages (from pandas->RGT) (2023.3)
Requirement already satisfied: zipp>=3.1.0 in ./.local/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib>=1.1.0->RGT) (3.15.0)
Requirement already satisfied: six>=1.5 in ./.local/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib>=1.1.0->RGT) (1.16.0)
Installing collected packages: RGT
Successfully installed RGT-1.0.0
MAC205928:~ diazmeco$ ls
Applications				cpdb-venv
Creative Cloud Files			gsea_home
Desktop					httpsanalysis.ingenuity.compa_4248295
Documents				httpsanalysis.ingenuity.compa_627256
Downloads				id_rsa
Dropbox					id_rsa.pub
GSVA					igv
Library					mambaforge
MoscatDiazMecoLab			med.cornell.edu
MoscatDiazMecoLab Dropbox		miniconda3
Movies					ncbi
Music					opt
OneDrive - med.cornell.edu		pathml
Pictures				pippo
Public					prefix
PycharmProjects				rose
SEACR					src
Sites					streamlit_apps
MAC205928:~ diazmeco$ brew install python boost llvm
Warning: python@3.11 3.11.3 is already installed and up-to-date.
To reinstall 3.11.3, run:
  brew reinstall python@3.11
Warning: boost 1.81.0_1 is already installed and up-to-date.
To reinstall 1.81.0_1, run:
  brew reinstall boost
Warning: llvm 16.0.5 is already installed and up-to-date.
To reinstall 16.0.5, run:
  brew reinstall llvm
MAC205928:~ diazmeco$ pip install cython numpy scipy
Requirement already satisfied: cython in ./.local/lib/python3.8/site-packages (0.29.35)
Requirement already satisfied: numpy in ./.local/lib/python3.8/site-packages (1.24.3)
Requirement already satisfied: scipy in ./.local/lib/python3.8/site-packages (1.10.1)
MAC205928:~ diazmeco$ pip install RGT --no-binary RGT
Requirement already satisfied: RGT in ./.pyenv/versions/3.8.2/lib/python3.8/site-packages (1.0.0)
Requirement already satisfied: cython in ./.local/lib/python3.8/site-packages (from RGT) (0.29.35)
Requirement already satisfied: numpy>=1.4.0 in ./.local/lib/python3.8/site-packages (from RGT) (1.24.3)
Requirement already satisfied: scipy>=1.0.0 in ./.local/lib/python3.8/site-packages (from RGT) (1.10.1)
Requirement already satisfied: pysam>=0.12.0 in ./.local/lib/python3.8/site-packages (from RGT) (0.21.0)
Requirement already satisfied: pyBigWig in ./.local/lib/python3.8/site-packages (from RGT) (0.3.22)
Requirement already satisfied: Biopython>=1.64 in ./.local/lib/python3.8/site-packages (from RGT) (1.81)
Requirement already satisfied: fisher>=0.1.5 in ./.local/lib/python3.8/site-packages (from RGT) (0.1.10)
Requirement already satisfied: moods-python>=1.9.4.1 in ./.local/lib/python3.8/site-packages (from RGT) (1.9.4.1)
Requirement already satisfied: scikit-learn>=0.19.0 in ./.local/lib/python3.8/site-packages (from RGT) (1.2.2)
Requirement already satisfied: hmmlearn==0.2.2 in ./.local/lib/python3.8/site-packages (from RGT) (0.2.2)
Requirement already satisfied: pandas in ./.local/lib/python3.8/site-packages (from RGT) (2.0.2)
Requirement already satisfied: logomaker in ./.local/lib/python3.8/site-packages (from RGT) (0.8)
Requirement already satisfied: pyx in ./.local/lib/python3.8/site-packages (from RGT) (0.16)
Requirement already satisfied: joblib in ./.local/lib/python3.8/site-packages (from RGT) (1.2.0)
Requirement already satisfied: seaborn in ./.local/lib/python3.8/site-packages (from RGT) (0.12.2)
Requirement already satisfied: adjustText in ./.local/lib/python3.8/site-packages (from RGT) (0.8)
Requirement already satisfied: matplotlib>=1.1.0 in ./.local/lib/python3.8/site-packages (from RGT) (3.7.1)
Requirement already satisfied: mpmath in ./.local/lib/python3.8/site-packages (from RGT) (1.3.0)
Requirement already satisfied: HTSeq in ./.local/lib/python3.8/site-packages (from RGT) (2.0.3)
Requirement already satisfied: matplotlib-venn in ./.local/lib/python3.8/site-packages (from RGT) (0.11.9)
Requirement already satisfied: natsort in ./.local/lib/python3.8/site-packages (from RGT) (8.3.1)
Requirement already satisfied: contourpy>=1.0.1 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (1.0.7)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (4.39.4)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (1.4.4)
Requirement already satisfied: packaging>=20.0 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (23.1)
Requirement already satisfied: pillow>=6.2.0 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in ./.local/lib/python3.8/site-packages (from matplotlib>=1.1.0->RGT) (5.12.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.local/lib/python3.8/site-packages (from scikit-learn>=0.19.0->RGT) (3.1.0)
Requirement already satisfied: pytz>=2020.1 in ./.local/lib/python3.8/site-packages (from pandas->RGT) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in ./.local/lib/python3.8/site-packages (from pandas->RGT) (2023.3)
Requirement already satisfied: zipp>=3.1.0 in ./.local/lib/python3.8/site-packages (from importlib-resources>=3.2.0->matplotlib>=1.1.0->RGT) (3.15.0)
Requirement already satisfied: six>=1.5 in ./.local/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib>=1.1.0->RGT) (1.16.0)

But the rgtdata folder in not in home. 
I also tried unistall and install using: 
pip install --user RGT --no-binary rgt
and 
pip install --user RGT --no-binary rgt
and 
pip install --user RGT --use-pep517 RGT
and still no rgtdata folder. 
Would you mind to help me please? 
Thanks!

**Comment by lzj1769** [comment]
Hi @mdu4003 

What about simply using:

`pip install RGT`

**Comment by priyagaddi** [comment]
I have installed RGT package v1.0.0, but it says rgt-hint command not found. Any suggestions ?

**Comment by lzj1769** [comment]
You need to make sure that the PATH is included in your enviroment variable.

Can you type `which python` and see where you installed the package?

**Comment by lzj1769** [comment]
Closed if no further questions and feel free to re-open it when needed.
