### ISSUE TITLE
Viz and TDF have no version option

### ISSUE THREAD

**Issue by fabioticconi** [CostaLab/reg-gen#27]
@jovesus could you add a ```--version``` option that uses the global ```__version__.py``` file to grab the current RGT version?

See motif analysis or HINT for how to do it in the same way we do.

**Comment by fabioticconi** [comment]
@jovesus it automatically closes when a new release is out, because the commit has "close" in the message :)

**Comment by jovesus** [comment]
So it will be closed only when the new version is released? I thought I
closed it already but I still see it in the issue page. This is why I try
to close it again....
Fabio Ticconi <notifications@github.com> schrieb am Do. 14. Sep. 2017 um
15:19:

**Comment by fabioticconi** [comment]
Yep it only closes when the commit goes to the master branch. Since we work
in the develop branch, it only goes to the master branch upon release. You
can leave it like this for now ;)
