### ISSUE TITLE
ImportError: cannot import name 'mat' from 'numpy' - issues with rgt-hint

### ISSUE THREAD

**Issue by RaghadShu** [CostaLab/reg-gen#275]
Hello,
Thank you for the great tool!

So I have installed RGT using conda as recommended, and I am interested in using `rgt-hint` but I keep getting this error:
`Traceback (most recent call last):
  File "/home/rshuwaikan/anaconda3/envs/rgt/bin/rgt-hint", line 5, in <module>
    from rgt.HINT.Main import main
  File "/home/rshuwaikan/anaconda3/envs/rgt/lib/python3.9/site-packages/rgt/HINT/Main.py", line 14, in <module>
    from rgt.HINT.Training import training_args, training_run
  File "/home/rshuwaikan/anaconda3/envs/rgt/lib/python3.9/site-packages/rgt/HINT/Training.py", line 10, in <module>
    from rgt.HINT.signalProcessing import GenomicSignal
  File "/home/rshuwaikan/anaconda3/envs/rgt/lib/python3.9/site-packages/rgt/HINT/signalProcessing.py", line 6, in <module>
    from numpy import exp, array, abs, mat, linalg, convolve, nan_to_num
ImportError: cannot import name 'mat' from 'numpy' (/home/rshuwaikan/anaconda3/envs/rgt/lib/python3.9/site-packages/numpy/__init__.py)`

I tried downgrading numpy using `pip install numpy==1.19.5` but I got this warning message + it didn't solve the problem:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.1 requires numpy>=1.20, but you have numpy 1.19.5 which is incompatible.
matplotlib 3.9.1 requires numpy>=1.23, but you have numpy 1.19.5 which is incompatible.
pandas 2.2.2 requires numpy>=1.22.4; python_version < "3.11", but you have numpy 1.19.5 which is incompatible.
scipy 1.13.1 requires numpy<2.3,>=1.22.4, but you have numpy 1.19.5 which is incompatible.
seaborn 0.13.2 requires numpy!=1.24.0,>=1.20, but you have numpy 1.19.5 which is incompatible.
Successfully installed numpy-1.19.5` 

I also tried to `pip uninstall rgt` then install it again via the development branch as suggested [here](https://github.com/CostaLab/reg-gen/issues/247#issuecomment-1503370382), but that still gives me the same error:
`Traceback (most recent call last):
  File "/home/rshuwaikan/anaconda3/envs/rgt/bin/rgt-hint", line 5, in <module>
    from rgt.HINT.Main import main
  File "/home/rshuwaikan/anaconda3/envs/rgt/lib/python3.9/site-packages/rgt/HINT/Main.py", line 14, in <module>
    from rgt.HINT.Training import training_args, training_run
  File "/home/rshuwaikan/anaconda3/envs/rgt/lib/python3.9/site-packages/rgt/HINT/Training.py", line 10, in <module>
    from rgt.HINT.signalProcessing import GenomicSignal
  File "/home/rshuwaikan/anaconda3/envs/rgt/lib/python3.9/site-packages/rgt/HINT/signalProcessing.py", line 6, in <module>
    from numpy import exp, array, abs, mat, linalg, convolve, nan_to_num
ImportError: cannot import name 'mat' from 'numpy' (/home/rshuwaikan/anaconda3/envs/rgt/lib/python3.9/site-packages/numpy/__init__.py)`

Note that this issue is only when I try running `rgt-hint`.. Using `rgt-THOR` doesn't seem to cause problems.. 

Many thanks in advance,
Raghad

**Comment by RaghadShu** [comment]
Update: 
One thing I did was go to this script `/anaconda3/envs/rgt/lib/python3.9/site-packages/rgt/HINT/signalProcessing.py` and replace `mat` from numpy with `asmatrix` because it seems like `mat` from numpy has been removed in version 2.0.0 (https://numpy.org/doc/stable/release/2.0.0-notes.html#numpy-2-0-python-api-removals)

**Comment by lzj1769** [comment]
Hi @RaghadShu 

Thanks for looking at the issue.
Do you mind submitting a pull request after fixing it?

Thanks,
Zhijian

**Comment by RaghadShu** [comment]
Sure no problem 👍
