### ISSUE TITLE
rgt_THOR failing

### ISSUE THREAD

**Issue by johnmous** [CostaLab/reg-gen#28]
THOR is run on 6 histone datasets with two conditions, two replicates and Input. Of the 6 histone datasets, 5 complete successfully and one fails with the following stack trace:

```
Call DPs on whole genome.
Computing read extension sizes for ChIP-seq profiles
Compute factors
Normalize input of Signal 0, Rep 0 with factor 0.103
Normalize input of Signal 0, Rep 1 with factor 0.249
Normalize input of Signal 1, Rep 0 with factor 0.666
Normalize input of Signal 1, Rep 1 with factor 0.782
Use global TMM approach 
Compute HMM's training set
Traceback (most recent call last):
  File "..../.local/bin/rgt-THOR", line 11, in <module>
    load_entry_point('RGT==0.9.9', 'console_scripts', 'rgt-THOR')()
  File ".../.local/lib/python2.7/site-packages/rgt/THOR/THOR.py", line 157, in main
    chrom_sizes, dims, inputs, tracker)
  File "..../.local/lib/python2.7/site-packages/rgt/THOR/THOR.py", line 87, in train_HMM
    init_alpha, init_mu = get_init_parameters(s0, s1, s2)
  File "..../.local/lib/python2.7/site-packages/rgt/THOR/neg_bin_rep_hmm.py", line 64, in get_init_parameters
    alpha = (var - mu) / np.square(mu)
RuntimeWarning: invalid value encountered in divide

```

**Comment by fabioticconi** [comment]
Hi @johnmous, sorry for the delay. Which version of RGT have you installed?

**Comment by johnmous** [comment]
Hi @fabioticconi. The version I installed and run is 0.9.9

**Comment by fabioticconi** [comment]
Let's see if we can solve this. Could you try to upgrade to the latest version (in case we are lucky and there was some sneaky bug in 0.9.9), and re-run it using the ```--debug``` option in the command line?

This should output more information as well as create some files with ```-s0```, ```-s1``` and ```-s2``` suffix.

If they are not too big, it would be great to see the content of those files, since they are used to calculate "mu" which, from your output, I assume having a strange value, eg a NaN.

**Comment by johnmous** [comment]
I run rgt_THOR v. 0.10.0 and This is the stack trace I get:


Call DPs on whole genome.
Computing read extension sizes for ChIP-seq profiles
Compute factors
Normalize input of Signal 0, Rep 0 with factor 0.103
Normalize input of Signal 0, Rep 1 with factor 0.249
Normalize input of Signal 1, Rep 0 with factor 0.666
Normalize input of Signal 1, Rep 1 with factor 0.782
Use global TMM approach 
Use scaling factor 0.502
Use scaling factor 0.99
Use scaling factor 3.456
Use scaling factor 3.677
Compute HMM's training set
Training set parameters: threshold: 1.6, diff_cov: 22
Final training set parameters: threshold: 1.6, diff_cov: 22
Traceback (most recent call last):
  File ".../thorPy2/bin/rgt-THOR", line 11, in <module>
    sys.exit(main())
  File ".../thorPy2/lib/python2.7/site-packages/rgt/THOR/THOR.py", line 157, in main
    chrom_sizes, dims, inputs, tracker)
  File ".../thorPy2/lib/python2.7/site-packages/rgt/THOR/THOR.py", line 87, in train_HMM
    init_alpha, init_mu = get_init_parameters(s0, s1, s2)
  File ".../thorPy2/lib/python2.7/site-packages/rgt/THOR/neg_bin_rep_hmm.py", line 65, in get_init_parameters
    alpha = (var - mu) / np.square(mu)
RuntimeWarning: invalid value encountered in divide


I get the same error with divide (divide with zero?)
I m attaching the s0, s1 and s2 files. I had a look, they only contain integers, no NaN


[thorH3K4me3.zip](https://github.com/CostaLab/reg-gen/files/1215480/thorH3K4me3.zip)

**Comment by fabioticconi** [comment]
Looks like ```s2``` has only zeroes in the first column. This will make the matrix ```mu``` having one cell equal to zero, and thus cause the runtime error in the division.

It looks like it's a bug on our side, probably, although it happens rarely. We'll take a look. Thanks for the report!

**Comment by KFDing** [comment]
Hi, @johnmous  Could you print out what configuration you use to analyse your data? Which options you have chosen?

**Comment by johnmous** [comment]
Hi @KFDing. Thank you and your colleagues for the quick response. 

This is the command submitted:
> ..../envs/thorPy2/bin/rgt-THOR THOR_H3K4me3.config --debug --report --no-gc-content --pvalue 0.01 --name H3K4me3 --output-dir ..../thorDiffPeakCallH3K4me3/

And this is the config file (THOR_H3K4me3.config):
> #rep1
> .../samples/S019VZH1_H3K4me3/S019VZH1_H3K4me3.filter.bam
> .../samples/S01D7UH1_H3K4me3/S01D7UH1_H3K4me3.filter.bam
> #rep2
> .../samples/Blueprint_S007DDH2_H3K4me3/Blueprint_S007DDH2_H3K4me3.filter.bam
> .../samples/Blueprint_S008H1H1_H3K4me3/Blueprint_S008H1H1_H3K4me3.filter.bam
> #inputs1
> .../samples/S019VZH1_Input/S019VZH1_Input.filter.bam
> .../samples/S01D7UH1_Input/S01D7UH1_Input.filter.bam
> #inputs2
> .../samples/Blueprint_S007DDH2_Input/Blueprint_S007DDH2_Input.filter.bam
> .../samples/Blueprint_S008H1H1_Input/Blueprint_S008H1H1_Input.filter.bam
> #genome
> .../GRCh38_no_alt_analysis_set/reference.fa
> #chrom_sizes
> .../GRCh38_no_alt_analysis_set.sizes.genome.txt

**Comment by KFDing** [comment]
Hi, @johnmous  
I couldn't use our data to replicate this error, could you kindly send us the copy of data, or the link of your download? So that we could solve the problem?

**Comment by fabio-t** [comment]
We did not have the resources to investigate this further, at this point we must close the issue.
