### ISSUE TITLE
Get rgtdata folder path from environment variable

### ISSUE THREAD

**Issue by fabioticconi** [CostaLab/reg-gen#33]
Right now, we store a file inside the actual installation directory of rgt. This file contains the rgtdata folder path, defaulting to the home directory.

This is very brittle, and also requires a custom ```setup.py``` which causes further problems with pip (when using global options).

A further, big problem of this approach is the following: if RGT is installed on a shared computer (eg, cluster/server), then only one shared rgtdata folder is allowed for all users.

A better approach is to check an environment variable RGTDATA. If not set, default to home directory. If set, use that one.

**Comment by jovesus** [comment]
Agreed.

*Joseph Chao-Chung Kuo*
