### ISSUE TITLE
Test Pysam 0.12.0 with RGT

### ISSUE THREAD

**Issue by fabioticconi** [CostaLab/reg-gen#36]
Looks like pysam 0.12.0 is out, and they also seem to have fixed MacOS support (good news for #17).

However, there seem to be some API changes. We are going to have to test all RGT tools before we modify the dependency requirement in setup.py.

**Comment by jovesus** [comment]
Hi, 
what part is under testing? There is some clearer function in version 12. It will be very good if we use version 12 only.
I can work on CoverageSet as well.

**Comment by fabioticconi** [comment]
All RGT must be tested. Including installation with and without pysam already installed, on Mac especially.

It must be tested thoroughly because I don't know what API changes have been introduced.

**Comment by jovesus** [comment]
how about we make a branch to test it?

*Joseph Chao-Chung Kuo*

**Comment by jovesus** [comment]
Hi,
I test pysam 12 in the branch below:
test_pysam_12

I fixed some issue but there are no big problem. Please check it when you have time. Once we all confirm, we can merge it into develop branch.
