### ISSUE TITLE
MD5 Checksum support

### ISSUE THREAD

**Issue by lzj1769** [CostaLab/reg-gen#38]
We should validate the downloaded file by MD5 checksum, to make sure the files are downloaded completely.

**Comment by fabioticconi** [comment]
Which files? If you are referring to the genomes downloaded via `setupGenomicData`, they are all downloaded through `wget -c` so that they can be interrupted and resumed. This behaviour would be disrupted by a MD5 checksum but we can think about it.

**Comment by lzj1769** [comment]
yes, some messages after downloading would be better.
