### ISSUE TITLE
Hint tutorial commands

### ISSUE THREAD

**Issue by DoaneAS** [CostaLab/reg-gen#44]
I get the following errors when attempting the commands in the tutorial:

```Error Number: 3.
Program: rgt-hint.
Report: The experimental matrix could not be loaded. Check if it is correctly formatted and that your python version is >= 2.7.
Behaviour: The program will quit with exit status 0.
--------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/rgt/HINT/Main.py", line 322, in main
    exp_matrix.read(input_matrix)
  File "build/bdist.linux-x86_64/egg/rgt/ExperimentalMatrix.py", line 66, in read
    f = open(file_path,'rU')
IOError: [Errno 2] No such file or directory: 'estimation'```

I believe I have version 10.2 installed correctly, but I do not see any documentation for commands like "rgt-hint estimate".  Can you please advise?

thanks

**Comment by lzj1769** [comment]
Hi Ashley,

Thanks for your interest!
We are going to release a new version of HINT, with some new features.
The complete documents will be available in coming days, so the webpage now is not stable,  
please just ignore it temporarily.

you can find an old tutorial here:
http://epigenomicstutorial-ismb2017.readthedocs.io/en/latest/Practical2.html#step1-footprint-calling

Sorry for the inconvenience.

**Comment by DoaneAS** [comment]
Hi @lzj1769, 
Great, thanks so much for the fast reply and update.  Looking forward to the new version of HINT!

Best, 
Ashley
