### ISSUE TITLE
"Average signal graph"'s logo part sometimes overlap the signal

### ISSUE THREAD

**Issue by lzj1769** [CostaLab/reg-gen#54]
Using rgt-hint differential command, the output line plots sometimes have overlap problem, making the sequence logo unclear.

**Comment by DoaneAS** [comment]
Along these lines, it would be great to add an option to write the footprinting results to a text file before plotting.  Ideally, this would be before aggregating the data, so for example a matrix where each row is a specific instance of the given motif.

thanks

**Comment by lzj1769** [comment]
Hi, @DoaneAS

Thanks for your suggestion, we will consider it in our next release.
