### ISSUE TITLE
"rgt-motifanalysis matching" Illegal Instruction Error

### ISSUE THREAD

**Issue by mdurante1** [CostaLab/reg-gen#57]
Hi, 

I am trying to run the "rgt-motifanalysis matching" command and I keep getting an Illegal instruction error followed by a core dump. I tried this on the example data provided and I still am receiving the same error. Do you have any guidance on how to resolve this?

Thanks,
Michael

```
[mdurante@pegasus RGT_MotifAnalysis_FullSiteTest]$ rgt-motifanalysis matching input/regions_K562.bed input/background.bed
>> genome: hg19
>> motif repositories: [u'hocomoco']
Illegal instruction (core dumped)
```

**Comment by fabio-t** [comment]
Hi Michael,

Can you post the output of both:

rgt-motifanalysis --version
python --version

Thanks,
Fabio

**Comment by mdurante1** [comment]
```
(atac_danpos) [mdurante@pegasus ~]$ rgt-motifanalysis --version
Motif Analysis - Regulatory Analysis Toolbox (RGT) - v0.11.1
(atac_danpos) [mdurante@pegasus ~]$ python --version
Python 2.7.14
```

**Comment by fabio-t** [comment]
What OS are you running?

**Comment by mdurante1** [comment]
```
[mdurante@pegasus ~]$ cat /etc/centos-release
CentOS release 6.5 (Final)
```

**Comment by fabio-t** [comment]
I'm a bit baffled. Does that happen immediately after the "hocomoco" line,
or after a bit of computation?

I will try it on a CentOS after the christmas vacations and see if I can
reproduce it. The only thing I can think of is some unsupported library
version linked to one of rgt's dependencie, causing a crash somewhere.

If you have the time and inclination, you could try to directly work with
MOODS and see if it's that library that crashes:

https://github.com/jhkorhonen/MOODS/wiki/Getting-Started#getting-started-with-python-libraries

**Comment by mdurante1** [comment]
It occurs immediately after the "hocomoco" line.

I will post on the MOODS page to see if they have any suggestions. In the meantime, is there another linux or OS X operating system that you recommend?

**Comment by fabio-t** [comment]
I would advise to write there only if you fail to run MOODS-specific
commands from the python shell, following the tutorial I linked - so we are
sure that it is MOODS-related.

You can run RGT on any desktop-based, recent linux OS (eg, Ubuntu/Mint
should work great, as long as you install a couple of dependencies with
apt-get, and I can help you with that) or on OS X (again, a few system-wide
libraries needed, I can you help with that too).

I guess other recent linux distributions should work, too.

**Comment by fabio-t** [comment]
RGT on MacOS requires a brew version of python, plus another couple of
things:

brew install python llvm boost

Then you need to fix the PATH, eg:

export PATH="$(brew --prefix)/opt/python/libexec/bin:/usr/local/bin:$PATH
echo 'export PATH="$(brew
--prefix)/opt/python/libexec/bin:/usr/local/bin:$PATH'
>> ~/.bash_profile

Then finally you can go ahead and install:

pip install cython numpy scipy
pip install rgt
pip install https://github.com/fabioticconi/MOODS/tarball/pypi-ready

Note that we don't use "--user" here, otherwise you'd have to add another
thing in the path. It's easier this way, since it doesn't require sudo.

Let me know if anything fails or is not clear.

Cheers,
Fabio

**Comment by fabio-t** [comment]
@mdurante1 I've just noticed that the formatting got screwed up, because I replied via email. Here's better:

RGT on MacOS requires a brew version of python, plus another couple of
things:

```
brew install python llvm boost
```

Then you need to fix the PATH, eg:

```
export PATH="$(brew --prefix)/opt/python/libexec/bin:/usr/local/bin:$PATH 
echo 'export PATH="$(brew --prefix)/opt/python/libexec/bin:/usr/local/bin:$PATH' >> ~/.bash_profile
```

Then finally you can go ahead and install:

```
pip install cython numpy scipy
pip install rgt
pip install https://github.com/fabioticconi/MOODS/tarball/pypi-ready
```

Note that we don't use "--user" here, otherwise you'd have to add another
thing in the path. It's easier this way, since it doesn't require sudo.

**Comment by fabio-t** [comment]
@mdurante1 incidentally, you could also try the following on CentOS: remove MOODS from conda, and install it via pip:

pip install https://github.com/fabioticconi/MOODS/tarball/pypi-ready

This is my "pip ready" copy of the latest version of MOODS, waiting for the author to support pypi :)

**Comment by souryacs** [comment]
Hi,
I am facing the same issue, when running RGT (installed latest version by pip) within a computing cluster via qsub command. 

Briefly, following commands work within qsub script.
rgt-hint --version
                HINT - Regulatory Analysis Toolbox (RGT) - v0.12.3
rgt-hint footprinting --help
               usage: rgt-hint footprinting [-h]......................

But, when I run
rgt-motifanalysis --version, or the command rgt-motifanalysis matching --help
                  ....Illegal instruction     (core dumped) rgt-motifanalysis --version

I am using Python 2.7.13. When I run these commands in a standalone linux machine (with same python version), they all work. I think the motif analysis tool is not working in the computing cluster. Is there any specific library dependency for the motif analysis tool? For your kind information, the cluster do not support any graphical visualization.
Please help. 

Thanks, 
Sourya

**Comment by YichaoOU** [comment]
got same issue here:

```
(rgt_hint) [yli11@nodecn046 atac_seq_footprint_yli11_2020-07-04]$ rgt-motifanalysis matching --organism hg19 --input-files t.bed --output-location t_motif_match
>> output location: t_motif_match
>> genome: hg19
>> pseudocounts: 1.0
>> fpr threshold: 0.0001
>>> input file t loaded: 14 regions
>> all files loaded
>> used database(s): jaspar_vertebrates
Illegal instruction
```

**Comment by YichaoOU** [comment]
Something relate to the HPC system. I'm OK with running it on some nodes, but not on others. But they are all red hat 7 systems.
