### ISSUE TITLE
rgt-hint differential error

### ISSUE THREAD

**Issue by mdurante1** [CostaLab/reg-gen#58]
Hi,

I am running RGT v0.11.1 on Python 2.7.14 in an Ubuntu 16.04 OS. I was able to run the "rgt-motifanalysis matching" command but when I run the "rgt-hint differential" I received the following error "TypeError: coercing to Unicode: need string or buffer, NoneType found". Do you have any suggestions to why this is occurring?

Thanks,
Michael

**Comment by lzj1769** [comment]
Hi @mdurante1 ,

you forgot to set option --mpbs-file2 in you command.

**Comment by mdurante1** [comment]
Thanks!
