### ISSUE TITLE
Release concept: to discuss and improve

### ISSUE THREAD

**Issue by fabio-t** [CostaLab/reg-gen#6]
The "releases" here are sub-project specific. However, we then use a link to Google Drive for the global "rgt" release.

We should instead provide a single RGT release here on github, including fixes for all subprojects. Users should stay up-to-date even if they use only, say "Odin", because we don't when they might want to try another of the tools.

Also they might benefit from bug fixes at the RGT top level: otherwise, any time we make a change at the top level we have to release a fix for ALL the tools. It's not scalable.

**Comment by fabioticconi** [comment]
The current approach of using one release version for all tools in the RGT toolbox seem to be very efficient.

One possible future modification is the following:

* split rgt-core, the actual library, from the tools
* each tool becomes its own python package (eg either called like rgt-THOR or just THOR)
* each tools has its own dependencies, but they all depend on rgt-core. There should never be inter-tool dependencies
* rgt-core and each tool keep their own versions and changelogs, and with time they can detach from the "rgt umbrella" to become their own isolated thing, if they get big/influential enough. Right now this isn't possible in a clean way

This would allow users to only install the tool they are actually interested in, or even just use rgt-core for their own tools.

I would see this being a single github repository with one submodule for each tool and one for rgt-core.
