### ISSUE TITLE
ValueError: fetch called on bamfile without index

### ISSUE THREAD

**Issue by kodayu** [CostaLab/reg-gen#70]
I don't know why I get this error information. It seems that pysam has some bugs, but hardly I can find the same problem as me. Can you help me? I am using rgt-THOR. I am sure that your get_extension_size.py may has some bugs.

**Comment by jovesus** [comment]
Hi,
Are the index files of those BAM files in the same folder? If not, could you try to generate them and test it again?
```
samtools index SAMPLE.bam
```
By the command above, SAMPLE.bam.bai will be generated. Please let us know whether it solves your problem or not.
