### ISSUE TITLE
rgt-hint footprinting - python3 - joblib pickle error

### ISSUE THREAD

**Issue by mcjmigdal** [CostaLab/reg-gen#74]
Hi,
I'm getting following error when running footprinting:

`ValueError: You may be trying to read with python 3 a joblib pickle generated with python 2. This feature is not supported by joblib.`

Any solution?

**Comment by lzj1769** [comment]
Hi, @mcjmigdal,

python3 is not fully supported so far, 
can you run footprinting under python2?

Best,
Li

**Comment by fabio-t** [comment]
Closing, since we don't support python 3.
