### ISSUE TITLE
THOR 0.11.3 parameter init error

### ISSUE THREAD

**Issue by ptrebert** [CostaLab/reg-gen#78]
Hi,
THOR 0.11.3 / Python 2.7 fails with
```
Compute HMM's training set
Train HMM
Traceback (most recent call last):
  File "/TL/epigenetics2/work/pebert/conda/envs/py2rgt/bin/rgt-THOR", line 11, in <module>
    sys.exit(main())
  File "/TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages/rgt/THOR/THOR.py", line 157, in main
    chrom_sizes, dims, inputs, tracker)
  File "/TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages/rgt/THOR/THOR.py", line 92, in train_HMM
    m.fit([training_set_obs], options.hmm_free_para)
  File "/TL/epigenetics2/work/pebert/conda/envs/py2rgt/lib/python2.7/site-packages/rgt/THOR/neg_bin_rep_hmm.py", line 125, in fit
    self._init(obs, self.init_params)
TypeError: _init() takes exactly 4 arguments (3 given)
```
Parameter `--merge` is set, normalization based on HK genes.

Best,
Peter

**Comment by fabio-t** [comment]
Hi, could you give us more information about this? The way you call THOR, for example, and the content of your config file.

**Comment by ptrebert** [comment]
Since I opened this bug report more than a year ago, no, I cannot provide any more details about what went wrong back then. Also, to me, the solution is no longer relevant, so feel free to close this issue.

**Comment by nikostrasan** [comment]
Hello @fabio-t , 
I am currently working with THOR and facing exactly the same issue with the:
TypeError: _init() takes exactly 4 arguments (3 given)

Is it possible to help me with this?
Thanks in advance,

Details:
Command line:
rgt-THOR Compar_analysis_THOR_.config -n Compare_bams3 --report  

config file:
#rep1
H3K27ac1_E70852.nodup.sorted.bam
H3K27ac2_E70846.nodup.sorted.bam
#rep2
H3K27acD1_E32815.nodup.sorted.bam
H3K27acD2_E20860.nodup.sorted.bam
#chrom_sizes
hg19_chromsizes.txt
#genome
hg19.fa
#inputs1
Input1_E70852.nodup.sorted.bam
Input2_E70846.nodup.sorted.bam
#inputs2
InputD1_E32815.nodup.sorted.bam
InputD2_E20860.nodup.sorted.bam

I am running it on Python2.7 .
