### ISSUE TITLE
ValueError in joblib pickle between Python 2 & 3

### ISSUE THREAD

**Issue by rbronste** [CostaLab/reg-gen#88]
Successfully downloaded and installed on high performance cluster, however with either Python version running getting the following when trying to run your ATAC demo:

```
rgt-hint footprinting --atac-seq ATAC.bam ATACPeaks.bed

ValueError: You may be trying to read with python 3 a joblib pickle generated with python 2. This feature is not supported by joblib.
```

**Comment by lzj1769** [comment]
@rbronste 

this means you are using python3, which is not fully supported so far.
Can you try python2 instead?
