### ISSUE TITLE
pysam cannot extract reverse read position

### ISSUE THREAD

**Issue by alexyfyf** [CostaLab/reg-gen#89]
Hi RGT group,

I had issue using HINT on ATAC-seq data. My code like below:
```
rgt-hint footprinting --atac-seq --paired-end --output-prefix=tets pHSC_SU048_chr.bam pHSC_SU048_peaks.narrowPeak --organism=hg19
```
And it throw out error:
```
Traceback (most recent call last):
  File "/usr/local/bin/rgt-hint", line 11, in <module>
    load_entry_point('RGT==0.11.4', 'console_scripts', 'rgt-hint')()
  File "/usr/local/lib/python2.7/dist-packages/rgt/HINT/Main.py", line 89, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/rgt/HINT/Footprinting.py", line 105, in footprinting_run
    atac_seq(args)
  File "/usr/local/lib/python2.7/dist-packages/rgt/HINT/Footprinting.py", line 252, in atac_seq
    min_length=None, max_length=145, strand=True)
  File "/usr/local/lib/python2.7/dist-packages/rgt/HINT/signalProcessing.py", line 935, in get_bc_signal_by_fragment_length
    cut_site = read.aend + reverse_shift - 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

I then tested on chr21 only and split it into reverse and forward reads in separate bam files.
It worked in forward strands but not reverse strand (reverse strand has same error).

I checked the manual of pysam, it says the `aend` is replaced by `reference_end`, I'm not familiar with python and don't know if it could be the cause.

Hope you can help.

Thank you.

**Comment by lzj1769** [comment]
Hi, @alexyfyf 

It could be that pysam has remove the `aend` option. 
Let's first check the pysam version,
open your terminal and enter `python`
type 
`import pysam`
`pysam.__version__`

my pysam version is 0.14.1 and HINT is working well.
if you installed higher version, like 0.15.0, you can downgrade it runnng following commands:
`pip uninstall pysam`
`pip install --user pysam==0.14.1`

We will chekc our RGT code to soon to reflect the new pysam.

Best,

**Comment by alexyfyf** [comment]
Yes, I'm using 0.15.1. 
```
ubuntu@general:~$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> pysam.__version__
'0.15.1'
```

But I separately tested the `aend` function on reverse and forward strand of chr22 separately. And it seems to be working. 
``` 
# test.py
import pysam
print pysam.__version__
bamfile = pysam.AlignmentFile("chr21_rev.bam","rb")
for read in bamfile.fetch('chr21', 258000, 300000):
     print read.aend
bamfile.close()

bamfile = pysam.AlignmentFile("chr21_for.bam","rb")
for read in bamfile.fetch('chr21', 258000, 300000):
     print read.aend
bamfile.close()
```

```
ubuntu@general:/Myvolume/fyan0011/atac_patient/hint_atac$ python test.py 
0.15.1
258131
260367
258131
260367
```

Finally, I think I solved this problem by filtering the bam files to only include reads with MAPQ > 30. And it works on chr22 of this dataset. So I'm not sure what caused this error.

I'm now testing on the whole dataset and it's still running. I'll post the result hopefully tomorrow.

Thank you very much.

**Comment by alexyfyf** [comment]
New error:
```
ubuntu@general:/Myvolume/fyan0011/atac_patient/hint_atac$ time rgt-hint footprinting --atac-seq --paired-end --output-prefix=test_filter pHSC_SU048_filter_chr.bam pHSC_SU048_filter_chr_peaks.narrowPeak

Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
Mean of empty slice.
invalid value encountered in double_scalars
divide by zero encountered in log
divide by zero encountered in log
Traceback (most recent call last):
  File "/usr/local/bin/rgt-hint", line 11, in <module>
    load_entry_point('RGT==0.11.4', 'console_scripts', 'rgt-hint')()
  File "/usr/local/lib/python2.7/dist-packages/rgt/HINT/Main.py", line 89, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/rgt/HINT/Footprinting.py", line 105, in footprinting_run
    atac_seq(args)
  File "/usr/local/lib/python2.7/dist-packages/rgt/HINT/Footprinting.py", line 252, in atac_seq
    min_length=None, max_length=145, strand=True)
ValueError: too many values to unpack

real    83m48.015s
user    282m9.040s
sys     687m29.279s
```
Can you have a look please? The input is filtered MAPQ > 30 and only chr1-22, X, Y, MT. Peak files is from MACS2 narrowpeak.

Thank you so much.

**Comment by lzj1769** [comment]
@alexyfyf ,

thanks for your feedback.

I note that there is MT chromosome in your BAM, which we usually remove it before predicting footprints.
Can you try this?

If it doesn't work, would you mind sharing your BAM file and peaks with us?
so I can try to reproduce the error and figure out what is going on.

Thanks,
Li

**Comment by alexyfyf** [comment]
Thank you @lzj1769  so much.

Removing MT doesn't help.  But I found my peaks have some duplicate regions because I set the `--call-summit` in macs2. So I removed these duplicate regions by not using call-summit when peak calling and finally footprinting worked for this sample. I'm now testing on other samples from the same pipeline.

I have another question regarding bias correction of ATAC-seq. I read your paper from bioRxiv and am wondering how can I set the VOM bias correction methods with current `rgt-hint footprinting`? Is it already implied when I set `--atac-seq`?

Thanks again.

Alex

**Comment by lzj1769** [comment]
@alexyfyf ,

> Removing MT doesn't help. But I found my peaks have some duplicate regions because I set the --call-summit in macs2. So I removed these duplicate regions by not using call-summit when peak calling and finally footprinting worked for this sample. I'm now testing on other samples from the same pipeline.

Thanks for your feedback. 
I hope RGT can be helpful for your research.

> I have another question regarding bias correction of ATAC-seq. I read your paper from bioRxiv and am wondering how can I set the VOM bias correction methods with current rgt-hint footprinting? Is it already implied when I set --atac-seq?

yes, you are right. the bias correction has been applied for ATAC-seq by default.
because we found that using bias-correction will improve the footprinting prediction.

Best,
Li

**Comment by alexyfyf** [comment]
Great. I think I can close the issue now. Thank you.
