### ISSUE TITLE
Failure to read experimental data should give more information

### ISSUE THREAD

**Issue by fabioticconi** [CostaLab/reg-gen#9]
Relevant code:

```
    try:
        exp_matrix = ExperimentalMatrix()
        exp_matrix.read(input_matrix)
    except Exception: error_handler.throw_error("FP_WRONG_EXPMAT")
```

If a file is not found/accessible, the error message should say so.

**Comment by fabioticconi** [comment]
this should probably be extended to all errors thrown

**Comment by eggduzao** [comment]
Dear all,

I am the one that created the error handling classes. They are on Util.py.
"FP_WRONG_EXPMAT" is only a label to the dictionary of real messages.

Best,

Eduardo

**Comment by fabioticconi** [comment]
Yep I know, but it doesn't give context information. Was the file not present? Which file? Was the file unreadable or badly formatted? I put this note here to remind myself to extend the error handling in the future ;)

**Comment by fabioticconi** [comment]
Added traceback, I think this is enough for now.
