### ISSUE TITLE
Segmentation fault (core dumped) error when creating .fpr file using createFpr.py

### ISSUE THREAD

**Issue by rdbcasillas** [CostaLab/reg-gen#94]
Hello,

I am trying to run the command `rgt-motifanalysis matching` for mm10. This script looks for a ".fpr" file which I do not have for mm10. I found the [createFpr.py](https://github.com/CostaLab/reg-gen/blob/master/data/motifs/createFpr.py) script but I get an error when I run the following command:

```
python2 createFpr.py hocomoco-mouse/pwm/ pwm.fpr

Segmentation fault (core dumped)
```

From the little debugging that I did, the error seems to be happening at the following line in the script: 

`pssm = tools.log_odds(pfm, bg, pseudocounts, 2)`

I have verified that MOODS is installed properly. 

Is there something else that i can try to understand this error? Any help will be greatly appreciated. Does RGT team has .fpr file for mm10 motif dataset that they can share? I see that it was provided for human dataset. 

Let me know if I need to provide more info.

Thank you!

**Comment by rdbcasillas** [comment]
Thank you @fabio-t for a detailed answer. It worked! "dash" in the name seems to be working too. 

Btw, if you accept contributions and pull requests, I am more than happy to help with automation, documentation or any other features that you are planning to add to the next release.

**Comment by fabio-t** [comment]
I'm glad it helped :) we are not currently looking for contributions, but thanks!
