### ISSUE TITLE
IndexError: list index out of range when I try to run rgt-hint

### ISSUE THREAD

**Issue by KHBHH** [CostaLab/reg-gen#95]
Hi everyone,

I am trying to run rgt-hint on a cluster. I have downloaded the chromosomes into mm9 using wget http://hgdownload.cse.ucsc.edu/goldenPath/mm9/chromosomes/chr1.fa.gz (and the same thing for chromosomes 2 to X & Y).

And After downloading Blood_Mus in my home directory, when I run rgt-hint I get the following error:

(env2) bash-4.2$ **cd Blood_Mus**
(env2) bash-4.2$ **rgt-hint footprinting --atac-seq --organism=mm9 ./CD4/ATAC.bam ./CD4**
[W::hts_idx_load2] The index file is older than the data file: ./CD4/ATAC.bam.bai
[W::hts_idx_load2] The index file is older than the data file: ./CD4/ATAC.bam.bai
Mean of empty slice.
invalid value encountered in double_scalars
Traceback (most recent call last):
  File "/home/kb246/env2/bin/rgt-hint", line 11, in <module>
    sys.exit(main())
  File "/home/kb246/env2/lib/python2.7/site-packages/rgt/HINT/Main.py", line 89, in m
    args.func(args)
  File "/home/kb246/env2/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line
    atac_seq(args)
  File "/home/kb246/env2/lib/python2.7/site-packages/rgt/HINT/Footprinting.py", line
    bias_table, genome_data.get_genome())
  File "/home/kb246/env2/lib/python2.7/site-packages/rgt/HINT/signalProcessing.py", l
    ref, start, end, forward_shift, reverse_shift)
  File "/home/kb246/env2/lib/python2.7/site-packages/rgt/HINT/signalProcessing.py", l
    fLast = af[0]
_**IndexError: list index out of range**_

Please can someone advice me how to fix this?

I also want to mention that I did not install mm9 using setupGenomicData.py, I did it by typing wget http://hgdownload.cse.ucsc.edu/goldenPath/mm9/chromosomes/chr1.fa.gz . (as well as for the other chromosomes)

The reason behind it is when I used setupGenomicData.py file to download the genome, I was getting an error regarding the reference link, which I realized that the path to get the genes is changed as shown in this link: ftp://ftp.sanger.ac.uk/pub/gencode/README.txt

I will appreciate your help!
Thank you 
Best Regards,
Karni Bedirian

**Comment by lzj1769** [comment]
@KHBHH 

you need to use the same reference genome as you used for alignment.
In the example data you downloaded, mm10 was used so here you need to set  --organism=mm10

We have already updated setupGenomicData.py to reflect this change, and this problem will be fixed in our next release.

Thanks,

**Comment by KHBHH** [comment]
Hi Li,

Thank you for getting back to me so quickly.

When I run the following I am getting an error such as:
*rgt-hint footprinting --atac-seq --organism=mm10 ./CD4/ATAC.bam
./CD4/ATACPeaks.bed --output-prefix=CD4Footprints*

IOError: error when opening file `/home/kb246/rgtdata/mm10/genome_mm10.fa`

And when I go back and check thisi file, it is around 0 KB, which makes
sense that there is no data.

I would appreciate your advice.

Thank you
Best Regards,
Karni Bedirian

**Comment by lzj1769** [comment]
@KHBHH ,

This problem is fixed in our new release,
see #96 

Thanks,
Li
